### ISSUE TITLE
[Feature]: Replace `Join the waitlist` CTA button when user is authenticated

### ISSUE THREAD

**Issue by mohouyizme** [typehero/typehero#1001]
### Description

When the user is authenticated, change the CTA button in the hero section from `Join the waitlist` to `Explore`.

<img width="522" alt="Screenshot 2023-10-30 at 09 38 50" src="https://github.com/typehero/typehero/assets/23297439/b4820cff-42c8-4ed2-887b-3d90c31c470c">

**Comment by AnuMessi10** [comment]
Hi @mohouyizme let me know if you can assign this to me, cheers!

**Comment by mohouyizme** [comment]
Resolved: https://github.com/typehero/typehero/pull/1002

**Comment by bautistaaa** [comment]
> Well I was waiting to begin the fix as I clearly requested to be assigned first, but someone else raised a PR and it got resolved/merged without any assignment.
> 
> I am not sure if that is how open source works or am I missing something from the contributing guidelines/code of conduct?
> 
> @mohouyizme
> 
> cc: @bautistaaa

typically the reporter gets first crack at it. also i’m not always looking at these as my life is busy as well so these things will be missed. sorry about that and hopefully you can find something else!

**Comment by mohouyizme** [comment]
> Well I was waiting to begin the fix as I clearly requested to be assigned first, but someone else raised a PR and it got resolved/merged without any assignment.
> 
> I am not sure if that is how open source works or am I missing something from the contributing guidelines/code of conduct?
> 
> @mohouyizme
> 
> cc: @bautistaaa

I appreciate your concern and I want to clarify that my intention was solely to suggest a feature. When I realized that someone had addressed the issue and submitted a pull request, I went ahead and closed it from my end.

**Comment by mohouyizme** [comment]
@AnuMessi10 btw there is another improvement if you want to contribute.

In the footer, there is a section with "Join the Waitlist." It would be ideal if this section is not visible to authenticated users.

<img width="1203" alt="Screenshot 2023-11-07 at 15 00 13" src="https://github.com/typehero/typehero/assets/23297439/da402d3e-42f1-4b60-8b2b-1edd0b6cc689">
