### ISSUE TITLE
Challenges are out of order

### ISSUE THREAD

**Issue by ethanleifer** [typehero/typehero#1007]
### What happened?

When on the explore page, the first challenge is `Generic Function Arguments` which isn't technically the first one in a section since it links to a previous challenge. As a new user, I was confused where to start. Do I click to the previous challenge or keep going with the current one?

Is there some kind of internal system for grouping these together, that would make this more intuitive?

In the Generic Function Arguments:
<img width="592" alt="Screenshot 2023-10-30 at 4 10 13 PM" src="https://github.com/typehero/typehero/assets/17654498/ffb781c7-969c-4c7e-ba27-5b85536c5c7f">

Explore page ordering:
<img width="1465" alt="Screenshot 2023-10-30 at 4 10 46 PM" src="https://github.com/typehero/typehero/assets/17654498/7f3c590b-d4c1-47a8-96c2-d8cc3982965f">

### What browsers are you seeing the problem on?

Safari

**Comment by bautistaaa** [comment]
fair point

i think all of our beginner challenges currently belong to the Typescript Foundations track which is in order. im unsure if it makes sense to order them here as there will be more beginner challenges that dont necessarily belong to track.

any thoughts here?

cc @dimitropoulos @ayrock-dev

**Comment by bautistaaa** [comment]
spoke to @boek 

i think initially we can make the first card a static card to put you in the Typescript Foundations track

**Comment by ayrock-dev** [comment]
I like that solution :+1: Tough when challenges are grouped and presented in different orders, but the content is authored in _track_ order. Something to chew on.

Alternatively, perhaps minimizing `"next"` or `"previous"` language on the challenges also helps them be presented in different orders.

```diff
- In a previous challenge on generic type arguments we saw a `Row` type
+ In the challenge for generic type arguments we saw a `Row` type
```

**Comment by dimitropoulos** [comment]
@bautistaaa @ayrock-dev There simply is no way for some of these things to not be sequenced.  Gotta run before you can walk and the challenges need to make _some_ kinds of assumptions about what prior knowledge the user has (that's the reason for the prerequisites array in the metadata).  It's important that it's a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph).

![](https://user-images.githubusercontent.com/15232461/275269839-874e02a9-2a95-44fc-8e38-943a60457da8.png)

As the challenges get into Easy/Medium/etc. then they basically assume you know all the fundamentals and the "order" is not important anymore.  That's where tracks really shine.

> Alternatively, perhaps minimizing "next" or "previous" language on the challenges also helps them be presented in different orders.

@ayrock-dev can you give me an example of how these two challenges in particular could be presented in the opposite order? I think that would help me understand what you're suggesting.  Concretely: how could you talk about constraints on type arguments before talking about type arguments themselves?

**Comment by bautistaaa** [comment]
the order is managed in the admin dashboard. i have to fix it atm but if you have an ideal order i can update in the db. i made a quick glance at the prereqs and did a rough ordering which can be seen on the tracks page. lmk what you think it should be and i can update. ill fix the admin dashboard so you can self serve as well

**Comment by bautistaaa** [comment]
agreed @dimitropoulos.

the admin dashboard is the place where you can self serve tracks (adding/ordering/creating). i messed it up though so i have a ticket to fix so take a look at the tracks page https://typehero.dev/tracks/typescript-foundations and lmk what should be tweaked. i did a rough ordering from glancing at the pre reqs.

ideally you'd self serve in the admin dashboard. ill give you access once i fix it! should be soon

**Comment by bautistaaa** [comment]
im going to close this and probably remove the beginners sections pointing users to the track
