### ISSUE TITLE
[Bug]: Unable to scroll to top with a really long solution.

### ISSUE THREAD

**Issue by is-it-ayush** [typehero/typehero#1011]
### What happened?

If you were to write a long enough solution for any solution. You're unable to scroll to the top to get to the `Preview` button (both via mouse or via keyboard arrow keys). The video below demonstrates the problem.

[Screencast from 2023-10-31 11-41-35.webm](https://github.com/typehero/typehero/assets/36449128/80350c53-dc48-4318-bf35-de71308a17e7)

### What browsers are you seeing the problem on?

All

**Comment by oreoluwa-bs** [comment]
Can I fix this?
