### ISSUE TITLE
[Feature]: Edit profile pic inside user profile.

### ISSUE THREAD

**Issue by Neon-20** [typehero/typehero#1015]
### Description

**I was wondering if the user can edit the profile picture of him/her-self that would be better.**

<img width="1280" alt="Screenshot 2023-11-01 at 00 50 44" src="https://github.com/typehero/typehero/assets/55043383/9cb9e7db-cfc6-449b-ad5c-ffa94571091b">

### Explanation

This would help people to edit their custom pics/avatars to their profiles.

**Comment by bautistaaa** [comment]
nothing that’s planned as of now. you’ll have to update your github image in the meantime

**Comment by Neon-20** [comment]
OKie, Dokie. If you need a PR for this , I will be up for it.
After looking at the code @bautistaaa
