### ISSUE TITLE
[Bug]: Unclear literalObject & missing almostPi on Literal Types challenge

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1017]
### What happened?

Challenge: https://typehero.dev/challenge/literal-types

To pass the literalObject test here are the current solutions

```ts
const literalObject: {
	origin: "far across the omniverse",
	command: "fetch",
	item: "the universe's ultimate cup of coffee (black)",
	time: "five Earth minutes"
} = {
	origin: "far across the omniverse",
	command: "fetch",
	item: "the universe's ultimate cup of coffee (black)",
	time: "five Earth minutes"
}
```

i noticed these didn't match the solution so just want to make sure if thats intended.

**Comment by is-it-ayush** [comment]
Update: I also noticed that `almostPi` is missing from the challenge description under "Solve the challenge" section & boiler challenge code. This should be mentioned in the solve section & also added to the initial code. 

> Instead of creating another issue, I'm adding it here since both problems belong to the same challenge.

So, these would be the updated objectives of the PR closing this issue,
- [ ] unclear `literalObject`.
- [ ] missing `almostPi`

**Comment by dimitropoulos** [comment]
@bautistaaa check out https://github.com/typehero/typehero/pull/1009.  I believe this was fixed there.  we sorta need to get that PR merged and over the line so we can be in a better place (i.e. one where we can not have problems like this where things are broken or can be made to break later)

**Comment by dimitropoulos** [comment]
ok, now that the above is merged I believe this is closed with https://github.com/typehero/typehero/pull/1009/files#diff-e0dfad0a22ca87d53ba2b65eb78baa989893ad02fd12293f7e630e83ec4155e3 but if not please do reopen and we can figure out what makes sense
