### ISSUE TITLE
[Bug]: Broken test cases in The `typeof` Operator

### ISSUE THREAD

**Issue by boek** [typehero/typehero#1018]
### What happened?

This first test case is 
```
type test_Width = Expect<Equal<
  Width,
  number
>>;
```
but the example code uses `type Width = typeof width`. `width` is defined as `const width = 700` which makes it not possible to use `typeof width` to satisfy the test case with `type Width = typeof width`. This is someone confusing as a first time user. A possible solution would be to define `width` as a `let` instead of a `const` and have the initial example code be `type Width = unkown // typeof width` to have the tests fail but continue to hint them towards the right direction.

**Comment by boek** [comment]
The same test case also has `any` which makes it impossible to pass.

**Comment by dimitropoulos** [comment]
You ain't kidding.  Sorry about that.  I believe this was fixed in https://github.com/typehero/typehero/pull/1009/files#diff-0099821cf4a3ad9e092b6bbc993e635912ee57521dbcce196ad5eaace3c49769 but if that's not correct please do reopen.
