### ISSUE TITLE
[Feature]: Add suspense loading files to each route

### ISSUE THREAD

**Issue by PhantomKnight287** [typehero/typehero#1023]
### Description

Creating a `loading.tsx` file for every route because right now moving from one route to the other(for example: profile to edit profile) takes a long time and in that time nothing is shown, I am just stuck at page 1 and suddenly I've new page in front of me which kindof ruins the user experience.

**Comment by Nkemjikanma** [comment]
Hey @PhantomKnight287 any designs for this? Is this something i can pick up?

**Comment by PhantomKnight287** [comment]
> Hey @PhantomKnight287 any designs for this? Is this something i can pick up?

I remember seeing a loading.tsx file in the repo, you can use that in every route

**Comment by aadamw** [comment]
Hey, @Nkemjikanma. Are you still working on this?

**Comment by Nkemjikanma** [comment]
Hey, @aadamw yes I am.
Will let you know if I give up.

**Comment by bautistaaa** [comment]
@aadamw @Nkemjikanma 

since the item isn’t too urgent it’s fine, normally after some time we’ll let someone else try to do it and first PR wins just for future reference!
