### ISSUE TITLE
[Bug]: Not enough color contrast for the 'Too short!' error message in comments section of a type challenge

### ISSUE THREAD

**Issue by chadstewart** [typehero/typehero#1029]
### What happened?

More of an accessibility bug.

The error message that comes up when the comment box is empty is too dark for the background which would make it difficult for users with color blindness issues to see the message.

Here an example of the bug:

![Screenshot from 2023-11-01 17-43-39](https://github.com/typehero/typehero/assets/11777161/01b36826-199b-4b8f-939a-b7d28cf6db4c)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```zsh
N/A
```

**Comment by markkhoo** [comment]
On it
