### ISSUE TITLE
[Bug]: IsUnion is already implemented

### ISSUE THREAD

**Issue by boek** [typehero/typehero#1030]
### What happened?

Opening [IsUnion!](https://typehero.dev/challenge/isunion) it looks like the type has already been defined in some helper definitions. This means we cannot redefine it

**Comment by dimitropoulos** [comment]
@boek sorry: I don't really have any visibility into the type-challenge imported ones and I wanna keep any bandwidth I have focused on the challenge infrastructure until it's all working well and the CI is hooked up and such.

**Comment by bautistaaa** [comment]
i’ll take this one!

**Comment by Hacksore** [comment]
ayo

https://github.com/typehero/typehero/blob/f8a5851130b193feb2e43b6c45a055f6bb2f573a/packages/monaco/src/editor-types.ts#L44-L50

**Comment by bautistaaa** [comment]
yup exactly. debating updating the type challenges to import their types
