### ISSUE TITLE
[Bug]: disable copy pasting from tests UI

### ISSUE THREAD

**Issue by is-it-ayush** [typehero/typehero#1032]
### What happened?

It's very easy for anyone to directly copy `Z` from `type X = Except<Equal<Y, Z>` and just use that as a solution instead. Pretty much speed-running the entire challenge. This applies to all challenges that rely on it. Need more comment on this though if it's needs fixing or not. There are multiple solutions,
- hide "Tests UI" & only let user rely on "solve the challenge" description. this imo is an ideal solution.
- only disable copy pasting

### What browsers are you seeing the problem on?

All

**Comment by bautistaaa** [comment]
if people want to cheat themselves that is really up to them. we have nothing to incentivize this. there are plenty use cases that you'd need to copy and paste from the tests especially on the more advanced challenges for debugging.

please put suggestings in the discord. issues are for bugs
