### ISSUE TITLE
[Feature]: Simplify 'Ctrl+S' Functionality in Editor to Prevent Default Save Prompt

### ISSUE THREAD

**Issue by Jacksonmills** [typehero/typehero#1050]
### Description

Pressing 'Ctrl+S' in the code editor triggers the browser's default save function. This behavior is counterintuitive for users accustomed to IDEs where 'Ctrl+S' typically saves progress within the app or performs another action, such as running tests. Disabling this or binding 'Ctrl+S' to a more useful function, like running tests, would enhance usability.

## Suggested Improvement:
1. Disable the default browser action for 'Ctrl+S' within the editor.
2. Optionally, bind 'Ctrl+S' to trigger the test suite for immediate feedback.

I am totally open to contributing as well! 🫡

### Explanation

This change would streamline the coding experience and align the editor's functionality with common developer practices, improving the platform's overall user experience.

**Comment by bautistaaa** [comment]
the best route would be to just disable the default behavior of ctrl/cmd s

test suites are “run” automatically since the type checker just runs after keystroke. saving would do anything either as it’s all stored in local storage

**Comment by Mahmoudgalalz** [comment]
@bautistaaa I can take this if its available

**Comment by bautistaaa** [comment]
sure!

> @bautistaaa I can take this if its available

**Comment by bautistaaa** [comment]
we could also just display a toast that their changes are saved locally (even though it happens by default) ill defer to you

**Comment by Mahmoudgalalz** [comment]
Liked it, Usually is a better experience

**Comment by Jacksonmills** [comment]
Yeah I should have actually put disabling it as the ideal solution! I was hoping to pick this one up personally but if its already taken I can just review <3

**Comment by Jacksonmills** [comment]
> we could also just display a toast that their changes are saved locally (even though it happens by default) ill defer to you

I like the idea of some feedback personally

**Comment by Jacksonmills** [comment]
> @bautistaaa I can take this if its available

Mind if I take it myself? Posted this first but was hoping to contribute!

**Comment by Mahmoudgalalz** [comment]
Just Go for it, I will be toning for your PR tmrw

**Comment by bautistaaa** [comment]
sounds good
