### ISSUE TITLE
[Bug]: very large content is not able to scroll on submission overview screen

### ISSUE THREAD

**Issue by zaCKoZAck0** [typehero/typehero#1054]
### What happened?

![image](https://github.com/typehero/typehero/assets/69889382/1bd5516e-c7d2-4bc6-8bdc-4bccfea10148)
I found this while submitting challenges, It didn't cross my mind while #1052 , Though it's merged I'll be putting a new PR soon.

**Comment by bautistaaa** [comment]
should we max height the code so they can see the recommendations?

**Comment by zaCKoZAck0** [comment]
> should we max height the code so they can see the recommendations?

Currently making it scrollable only, but this should work too I guess.

**Comment by bautistaaa** [comment]
> > should we max height the code so they can see the recommendations?
> 
> Currently making it scrollable only, but this should work too I guess.

yeah sorry i should clarify, scrolling is still acceptable im just worried about a situation where the submission is so long they don’t even know there’s recommendations. this will be pretty common for the more advanced challenges

**Comment by zaCKoZAck0** [comment]
> > > should we max height the code so they can see the recommendations?
> > 
> > 
> > Currently making it scrollable only, but this should work too I guess.
> 
> yeah sorry i should clarify, scrolling is still acceptable im just worried about a situation where the submission is so long they don’t even know there’s recommendations. this will be pretty common for the more advanced challenges

Ya I thought of that too, One thing we can do is put suggestion on top and solution on bottom, also the other possible thing I can think of is putting an `id` on suggestions element and passing it in the url during redirect so it auto scrolls to suggestions.

**Comment by bautistaaa** [comment]
not a bad idea! i think just keep it simple for now i guess i think for 90% of users this will be fine
