### ISSUE TITLE
[Feature]: Redirect to /@[username] page after submitting profile update

### ISSUE THREAD

**Issue by aadamw** [typehero/typehero#1057]
### Description

Hey,
I noticed that when the user submits settings form on the `/settings` page, he's not redirected to profile page (`/@[username]`) automatically. In order to return to his profile page, he needs to additionally press a button.
Making this redirect automatically would improve UX.  

Step-by-step:
1. User visits `/settings` page
2. User updates bio/personal links
3. User clicks the "Update Profile" button
4. User is redirected back to `/@[username]` page

Current behavior:

https://github.com/typehero/typehero/assets/131662061/5e5776be-5c89-4719-8dee-174cde94e07a

Suggested behavior:

https://github.com/typehero/typehero/assets/131662061/18644607-6502-411f-939f-3200bebc49c6

**Comment by aadamw** [comment]
@bautistaaa wdyt?

**Comment by odicho** [comment]
@aadamw Hi, I definitely understand your perspective here. I do think that since these are separate pages, it will be annoying if you are redirected when you save. It's not an intuitive behavior in my opinion. Let me know what you think, otherwise we can close this!

**Comment by aadamw** [comment]
@odicho Thanks for sharing your opinion
It would make sense for me not to redirect the user back to the previous page if there were other actions on this page with separate CRUD actions. In this case we have single save button. After user clicks it, there is nothing more to do on this page. That's why IMO, user should be redirected back to profile page.

**Comment by bautistaaa** [comment]
I think the current behavior is fine for now. It will also inevitably grow in the next phase.

If I hear anymore complaints from early access users about this I'll reconsider
