### ISSUE TITLE
[Feature]: add a default title for solutions

### ISSUE THREAD

**Issue by Dun-sin** [typehero/typehero#1059]
### Description

It's required to have a title, but most people aren't creative about it. It can be autogenerated e.g `${username}'s solution` filled in the input box, which the user can either remove it and add their custom title or leave it as it is

![image](https://github.com/typehero/typehero/assets/78784850/337a92dd-8fc1-487b-b56c-d47947a68933)

**Comment by Dun-sin** [comment]
can i take this when #1068 gets merged

**Comment by bautistaaa** [comment]
> can i take this when #1068 gets merged

you can do it now in parallel if you want

**Comment by Dun-sin** [comment]
> > can i take this when #1068 gets merged
> 
> you can do it now in parallel if you want

i would prefer to work on it after the other is merged
