### ISSUE TITLE
[Bug]: Challenge OG image does not render correctly on twitter

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1060]
### What happened?

I think the image needs to be resized to the appropriate dimensions to avoid cropping

<img width="658" alt="CleanShot 2023-11-06 at 07 17 48@2x" src="https://github.com/typehero/typehero/assets/3660667/382a3c2e-4393-4a2e-854e-6553ae412830">

**Comment by aadamw** [comment]
Would love to fix this
