### ISSUE TITLE
[Feature]: prevent solutions from being accessed

### ISSUE THREAD

**Issue by Dun-sin** [typehero/typehero#1069]
### Description

Users can easily access solutions without attempting to solve it themselves. It's not a challenge if i can easily access the solutions then it's not a challenge anymore.

Ways of which i think it can be done:
- if an x amount of submissions of unaccepted users shouldn't be able to access the submissions page
- only explanations(text) be shown but code shouldn't if x amount of unaccepted submissions

**Comment by bautistaaa** [comment]
A couple thoughts here:

- if a user wants to cheat themselves im okay with that
- unsure what this means `if an x amount of submissions of unaccepted users shouldn't be able to access the submissions page`
- `only explanations(text) be shown but code shouldn't if x amount of unaccepted submissions` we dont have the content to support this

i think maybe eventually we can prohibit this but we don't have the content atm to give "hints" or explanations. a good portion of these are ported from the type challenges repository

**Comment by Dun-sin** [comment]
> A couple thoughts here:
> 
> * if a user wants to cheat themselves im okay with that
> * unsure what this means `if an x amount of submissions of unaccepted users shouldn't be able to access the submissions page`
> * `only explanations(text) be shown but code shouldn't if x amount of unaccepted submissions` we dont have the content to support this
> 
> i think maybe eventually we can prohibit this but we don't have the content atm to give "hints" or explanations. a good portion of these are ported from the type challenges repository

i understand, should i close this then
