### ISSUE TITLE
[Bug]: profile/completed page has wrong submission time

### ISSUE THREAD

**Issue by manpreeeeeet** [typehero/typehero#1082]
### What happened?

![Screenshot_20231108_204659](https://github.com/typehero/typehero/assets/93985396/597e798d-62ae-45cd-b3cd-1d4be4031732)
[](url)

Last submission is incorrect, I didn't submit anything 5 hours ago, it's a few days old.

**Comment by ja153903** [comment]
@manpreeeeeet Are you sure you didn't do a problem and forget about it?

The query itself is pretty simple.

```tsx
async function getCompletedChallenges(userId: string) {
  const challenges = await prisma.challenge.findMany({
    where: {
      submission: {
        some: {
          userId,
          isSuccessful: true,
        },
      },
    },
    select: {
      id: true,
      slug: true,
      name: true,
      submission: {
        orderBy: {
          createdAt: 'desc',
        },
        take: 1,
        select: {
          createdAt: true,
        },
      },
    },
  });

  return challenges.sort(
    (challengeA, challengeB) =>
      new Date(challengeB.submission[0]!.createdAt).getTime() -
      new Date(challengeA.submission[0]!.createdAt).getTime(),
  );
}
```

We just take the latest submission from every completed challenge.

**Comment by manpreeeeeet** [comment]
I clicked on of the solved problem and last submission there is 7 days older so yeah, it's not something accidental. Maybe the UI is displaying it wrong.

**Comment by zaCKoZAck0** [comment]
Yes @manpreeeeeet  there's a problem with the time function 
cc: @bautistaaa

**Comment by bautistaaa** [comment]
fixed
