### ISSUE TITLE
[Feature]: Add number of problems solved 

### ISSUE THREAD

**Issue by manpreeeeeet** [typehero/typehero#1083]
### Description

another suggestion: can add how many problems i have solved in profile. also how many hards/easy/medium division

**Comment by zaCKoZAck0** [comment]
I have some ideas.

**Comment by me-imfhd** [comment]
like the leetcode right?

**Comment by bautistaaa** [comment]
> like the leetcode right?

@zaCKoZAck0 is cooking on it in the discord. would recommend joining and collaborating in the contributors channel

**Comment by me-imfhd** [comment]
oh then i am getting in

**Comment by zaCKoZAck0** [comment]
Will def appreciate the ideas.
