### ISSUE TITLE
[Bug]: toasts theme off for success toasts

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1085]
### What happened?

<img width="425" alt="CleanShot 2023-11-09 at 16 17 03@2x" src="https://github.com/typehero/typehero/assets/3660667/552eafa3-afff-408a-b0cb-5e6eb1f2b7be">

<img width="407" alt="CleanShot 2023-11-09 at 16 17 20@2x" src="https://github.com/typehero/typehero/assets/3660667/03cd871c-6e1c-4836-8fd7-5914e5df02c2">

**Comment by me-imfhd** [comment]
hey @bautistaaa i set up the project locally i tried using the toast, whats the issue here?

**Comment by bautistaaa** [comment]
> hey @bautistaaa i set up the project locally i tried using the toast, whats the issue here?

the colors are totally off, see the screen shots. text should be white. hover should not be black

**Comment by me-imfhd** [comment]
@bautistaaa what is the desired output then?

**Comment by me-imfhd** [comment]
Raised a pr trying to fix this issue
