### ISSUE TITLE
[Bug]: Comments pagination doesn't reset correctly

### ISSUE THREAD

**Issue by aadamw** [typehero/typehero#1095]
### What happened?

A bug happened!

In this case we should load comments from previous page

https://github.com/typehero/typehero/assets/131662061/de07f022-6e50-47e8-854a-0c44f94eed3e

### What browsers are you seeing the problem on?

All

**Comment by me-imfhd** [comment]
alright i think the issue is deleting the only left comment in older pages does not rerended  previous (newer comments page)... hmmm

**Comment by aadamw** [comment]
@me-imfhd fyi, I'm working on the fix

**Comment by me-imfhd** [comment]
Ok @aadamw let me know if you were able to fix it or facing problems, i was also working on that
