### ISSUE TITLE
[Bug]: Highlighting text makes it invisible

### ISSUE THREAD

**Issue by borisnezlobin** [typehero/typehero#1097]
### What happened?

In the markdown editor (on the solutions page, possibly elsewhere; I don't know where else the markdown textbox is used), when highlighting text (of any color), the text becomes invisible:
before:
<img width="491" alt="image" src="https://github.com/typehero/typehero/assets/146669165/2a999f05-8d20-496b-a6a2-34a4bf4c4c03">
after:
<img width="470" alt="image" src="https://github.com/typehero/typehero/assets/146669165/4bca1eae-6189-4ba4-bc59-be9db1ccbb7c">

### What browsers are you seeing the problem on?

Firefox

**Comment by odicho** [comment]
I honestly have no idea what to do about this

The package's demo website itself has this exact same behavior:
![image](https://github.com/typehero/typehero/assets/53154523/d5195a14-ce4f-42eb-b659-88663ca0fef5)

I tried overriding the styles, but it seems like they have some `!important` set, which makes it a little difficult to override.


I tried searching for open/closed issues [here](https://github.com/uiwjs/react-markdown-editor/issues), but couldn't find anything related to this (strange). I tried searching for "firefox" and "selection". 
cc: @bautistaaa

**Comment by me-imfhd** [comment]
i think like when we select stuff they maybe just make whatver is selected to background the color of selected thing, my intution says that if we can manipulate that css then something can be done
just dropping my thoughts (i have never worked with markdowns in past)

**Comment by borisnezlobin** [comment]
I'll see if we can do any black magic on it (to my limited ability), but it might be worth addressing the problem at the package itself

**Comment by borisnezlobin** [comment]
interesting: on chrome, highlighting the text only darkens the text, but doesn't make it invisible. is that preferable to no change to highlighted text? I'll see if I can fix it sometime today
<img width="540" alt="image" src="https://github.com/typehero/typehero/assets/146669165/9efc9964-4f82-4b0e-a04f-be7f21e41b50">

**Comment by borisnezlobin** [comment]
Interesting: it's not just the markdown editor that has this issue.

here are some screenshots throughout TypeHero (all the screenshots are on firefox, but chrome and safari have different and less impactful behaviour):
<img width="250" alt="image" src="https://github.com/typehero/typehero/assets/146669165/12b886ac-a93d-40c6-b506-aea44ad40000">
<img width="250" alt="image" src="https://github.com/typehero/typehero/assets/146669165/dd5951ed-04c9-4ec1-bd0f-ead2f3765431">
<img width="250" alt="image" src="https://github.com/typehero/typehero/assets/146669165/439f75d0-95c3-4163-ad57-0238d8ff87ff">


Badges in particular seem to have this issue (on firefox)... aaaand I've figured out why the issue is being caused.

For the badges, we are using a combination of `bg-clip-text` and `text-transparent` to create the nice effect of gradient text that lines up with the background color... which means that when we select the text, it stops being the background color and becomes just transparent. we can fix this with the tailwind `selection:` thingy to get somewhat accurate results (using something like `"selection:text-white selection:bg-blue-500/50"`), but this kind of fix isn't _perfect_ (and it might have some a11y concerns? idk):
<img width="553" alt="image" src="https://github.com/typehero/typehero/assets/146669165/9ea048ec-bd62-4053-8ad2-1fe352b9199d">
that's one way of solving the problem, the only other way I could think of is to not use text-transparent with bg-clip, but that would take away some goodlooking-ness
