### ISSUE TITLE
[Feature]: upgrade nextauth to v5 beta

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1099]
### Description

this will allow us to login on preview environments. we can also just get rid of staging completely at that point

https://github.com/nextauthjs/next-auth/tree/main/apps/proxy

https://authjs.dev/getting-started/deployment#securing-a-preview-deployment

**Comment by zaCKoZAck0** [comment]
[clerk.com](https://clerk.com/) ??

**Comment by rbrtj** [comment]
Raised a PR with just a nextauth upgrade:
https://github.com/typehero/typehero/pull/1105
