### ISSUE TITLE
[Bug]: Track UI on challenge view pushes comments UI offscreen

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1104]
### What happened?

Comment section is not account for the extra space the tracks ui occupies at the top of the panel so its offset

https://typehero.dev/challenge/generic-function-arguments

unable to scroll down farther to see then bottom
![image](https://github.com/typehero/typehero/assets/3660667/a1de897e-eb98-460f-855d-d0f910e1b43c)

**Comment by aadamw** [comment]
On it

**Comment by me-imfhd** [comment]
working on it... assign me this issue

**Comment by bautistaaa** [comment]
updated description and DM'd you a token @me-imfhd
