### ISSUE TITLE
[Feature][Advent of TypeScript 2023]: Content

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#1119]
### Description

⚠️ This is not ready for work. Join Discord to discuss with contributors on selecting 12 existing challenges for this.

#### References

 - https://github.com/typehero/typehero/discussions/1078

#### Requirements

The Twelve Days of TypeScript can be built out with 12 existing challenges on TypeHero, ramping from Beginner to Hard difficulty.

**Comment by bautistaaa** [comment]
going to compile a list of twelve and get thoughts
