### ISSUE TITLE
[Feature][Advent of TypeScript 2023]: Holiday Challenge Card UI

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#1121]
#### References

 - https://github.com/typehero/typehero/discussions/1078

#### Requirements

* On the Explore page, challenges in the Advent of TypeScript track can be rendered with a new card variant.
* Design Inspo:
  * challenge card arranges triangles into an 🌲 
  * challenge card has snowfall. for inspiration: https://codepen.io/ste-vg/pen/GqaZbo
* These cards will be "locked" until each day is revealed. For example, on Day 1 only the Day 1 card is available to see and click on. The rest will be disabled and just teasers.
* 
This should be hard-coded to display by the Advent of TypeScript slug and checking the holiday event feature flag.

💡 Note: Use holdayFoo rather than adventOfTypeScriptFoo for shorter variable names, and does not lock-in the name of the holiday event in the code. However, the public-facing slug should be the full event name.

```ts
const isHolidayEvent = featureFlags.enableHolidayEvent;
```

**Comment by tnarla** [comment]
hi

**Comment by bautistaaa** [comment]
![image](https://github.com/typehero/typehero/assets/3660667/4cb7e936-bdac-4bb2-a972-22323d1558c4)

**Comment by ayrock-dev** [comment]
Adding to description:
 - These cards will be "locked" until each day is revealed. For example, on Day 1 only the Day 1 card is available to see and click on. The rest will be disabled and just teasers.

**Comment by ayrock-dev** [comment]
some other inspo
![image (1)](https://github.com/typehero/typehero/assets/7817695/2aa85d76-37fe-4bf3-84f6-f95ecb6ea14f)

**Comment by ayrock-dev** [comment]
closed by #1140
