### ISSUE TITLE
[Feature][Advent of TypeScript 2023]: Holiday Hero/Feature Banner

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#1122]
#### References

 - https://github.com/typehero/typehero/discussions/1078

#### Requirements

Advent of TypeScript can be advertised at the top of the Explore page. This banner funnels and directs users who land on TypeHero towards Advent of TypeScript.

This should be hard-coded to display by checking the holiday event feature flag.

💡 Note: Use holdayFoo rather than adventOfTypeScriptFoo for shorter variable names, and does not lock-in the name of the holiday event in the code. However, the public-facing slug should be the full event name.

```ts
const isHolidayEvent = featureFlags.enableHolidayEvent;
```

**Comment by ayrock-dev** [comment]
rough mock, let's do some animated snow like https://codepen.io/ste-vg/pen/GqaZbo

![image](https://github.com/typehero/typehero/assets/7817695/e7693951-1374-49ae-812c-565c415924ff)

**Comment by maxdemaio** [comment]
This is what I came up with in HTML/CSS/JS. If anyone has anything they'd like to suggest please feel free! Lmk if we'd want to go forward w/ this and if not no worries.

https://github.com/typehero/typehero/assets/44373521/6f4b39cf-74aa-4a8c-a8fa-75ab71867748

**Comment by maxdemaio** [comment]
Original codepen in HTML/CSS/JS: https://codepen.io/nw/pen/WQmxYY
