### ISSUE TITLE
[Bug]: Line Height and spacing of Code Blocks

### ISSUE THREAD

**Issue by markkhoo** [typehero/typehero#1131]
### What happened?

Per @bautistaaa lets add some space between Code Blocks along the y-axis, line-to-line. This can enhance readability. 

![Capture](https://github.com/typehero/typehero/assets/79437064/a674ddfc-a3bc-456c-adbb-20fe46d31dbf)

### What browsers are you seeing the problem on?

All

**Comment by nathanroark** [comment]
Which challenge is this for? hit me with a link

**Comment by bautistaaa** [comment]
@nathanroark https://typehero.dev/challenge/awaited/solutions/51

**Comment by markkhoo** [comment]
> Which challenge is this for? hit me with a link
> 
> ![Screenshot from 2023-11-15 20-53-03](https://user-images.githubusercontent.com/30080693/283306738-3f0ed36f-c193-4c23-8c43-5b47cc806137.png)
> 
> Unable to see this issue on my browsers. Chrome/Firefox Ubuntu 23.10

Something going on with the font between different machines?

**Comment by nathanroark** [comment]
Kinda, I just checked with my Windows 11 machine, looks the same on it as on macOS. Ubuntu just doesn't have the font that is being used is my guess. I'll fix this issue for Windows & macOS
