### ISSUE TITLE
[chore]: Comment last edited section needs some space.

### ISSUE THREAD

**Issue by zaCKoZAck0** [typehero/typehero#1133]
### What happened?

Need to add some space between 'Last edited at' and Date
![image](https://github.com/typehero/typehero/assets/69889382/60b708a3-2b0c-4293-a8d3-dd21cff9d931)

**Comment by me-imfhd** [comment]
I can fix it, can you assign me this

**Comment by bautistaaa** [comment]
this is fixed already i believe

**Comment by bautistaaa** [comment]
nevermind
