### ISSUE TITLE
[Bug]: Solution editor all normal text get invisible when editing

### ISSUE THREAD

**Issue by me-imfhd** [typehero/typehero#1141]
### What happened?

A bug happened!
When in the solution editor i just even click any key for writing, something triggers and normal text gets invisible,

when writing the solution for first time this does not seem to happen, but on editing it happens
also can't see what i am editing

**Comment by me-imfhd** [comment]
[Screencast from 17-11-23 10:34:55 PM IST.webm](https://github.com/typehero/typehero/assets/114667178/93b42bbb-9da7-48c6-b121-73c6e0d3f23c)

**Comment by bautistaaa** [comment]
what browser. looks fine in chrome

**Comment by me-imfhd** [comment]
same chrome

**Comment by nathanroark** [comment]
I replicated it on Safari.

<img width="484" alt="Screenshot 2023-11-18 at 5 58 04 PM" src="https://github.com/typehero/typehero/assets/30080693/2a8d34bb-de62-4ede-b368-96a0217a2990">

**Comment by nathanroark** [comment]
## I was able to replicate with all other browsers now.

### Replication steps:
1. Set system theme to Dark Mode
2. Open Incognito Tab
3. Open TypeHero
4. Login
5. Go to a challenge solution you can edit
6. In edit mode, add a character.

### Thoughts as to cause of bug:
Theme in the rich markdown editor is set by default based off of system theme by default and the system option for the theme is not dark mode friendly.

**Comment by nathanroark** [comment]
Uploading Screen Recording 2023-11-18 at 11.26.31 PM.mov…
