### ISSUE TITLE
[Feature][Advent of TypeScript 2023]: Share URL

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#1143]
#### References

* https://github.com/typehero/typehero/discussions/1078

#### Requirements

Build a share URL which renders an link preview (open-graph (OG) image) for Advent of TypeScript.

Implement og image for:
* `typehero.dev/(username)?event=aot-2023`
  * This link preview is specific to the user.
  * Show stars for the number of completed Advent of TypeScript track challenges.
  * Re-use design elements from Advent of TypeScript banner.
* `typehero.dev/aot-2023`
  * This link preview would be the same for all users.
  * (No username. No stars).

These can be built using TypeHero's `og-image` app:
https://github.com/typehero/typehero/tree/main/apps/og-image

**Comment by ayrock-dev** [comment]
Design Mock

<img width="450" alt="image" src="https://github.com/typehero/typehero/assets/7817695/992e26c4-98ab-4132-b45e-75acd64f0885"><br />

Background for this image should re-use design from the Advent of TypeScript feature banner/hero shown below

https://x.com/trashh_dev/status/1725303221194010634?s=20
<img width="450" alt="image" src="https://github.com/typehero/typehero/assets/7817695/bea0df70-85f4-4419-abd0-6e3300add8c9">

**Comment by zaCKoZAck0** [comment]
@ayrock-dev I might need the codepen of banner shared on twitter.
