### ISSUE TITLE
[Bug]: Your code has been saved success toast is blank

### ISSUE THREAD

**Issue by paulle7** [typehero/typehero#1145]
### What happened?

When saving progress, the Your code has been saved success toast is blank.

<img width="884" alt="image" src="https://github.com/typehero/typehero/assets/70828466/454dd587-12d7-458a-b7a1-220cbd7bd5e6">

### What browsers are you seeing the problem on?

All

**Comment by zaCKoZAck0** [comment]
Yes, it's not blank, the text is also white. Fixing ASAP.

**Comment by paulle7** [comment]
> Yes, it's not blank, the text is also white. Fixing ASAP.
Yeah, not blank, just white.

It's because it's missing a toast `variant`.

**Comment by paulle7** [comment]
@zaCKoZAck0 feel free to assign this to me if you'd like and I'll push up the fix :)

**Comment by paulle7** [comment]
PR created https://github.com/typehero/typehero/pull/1147
