### ISSUE TITLE
Enable unused imports in lint config

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1163]
### Description

i dont know why it wasnt enabled to begin with. please enable and fix all errors

**Comment by maxdemaio** [comment]
I can pick this puppy up

**Comment by maxdemaio** [comment]
Adding this for refrence: https://turbo.build/repo/docs/handbook/linting/eslint

**Comment by maxdemaio** [comment]
Made changes that allow eslint to flag this as an error on the dev branch. Now we'd just need to apply that rule and fix only those unused imports.

**Comment by aadamw** [comment]
Thanks for picking it up @maxdemaio ❤️
