### ISSUE TITLE
[Bug]: challenges/validate.ts doesn't support dirs of challenges

### ISSUE THREAD

**Issue by heathhenley** [typehero/typehero#1174]
### What happened?

Run: 
`pnpm run lint:markdown:validate`

It's treating all the dirs in challenges as the ids, so it fails when the advent of typescript one `aot` doesn't have a `metadata.json`.

**Comment by mdwiltfong** [comment]
I've created a PR that will ignore the `aot` directory, but additional work will need to be done in order to validate aot seasons.
