### ISSUE TITLE
[Feature]: Indicate that a track is finished

### ISSUE THREAD

**Issue by MuhammadM1998** [typehero/typehero#1178]
### Description

Thanks a lot for the website, it's Amazing!

May I suggest that the UI reflects that a user finished all the track tasks. For example, in the below screenshot, instead of the blue progress bar indicating that it's still in progress, it should be green indicating that it's finished, and maybe some message & icon.

People are driven by progress & prizes. that green bar is the prize that tells the person 'Congratz, you did it! keep up the good work!' I'd suggest also a modal or something that shows up on finishing the track that prompts the user to share to social platforms to gain more traction for the site.

![Screenshot 2023-11-24 142756](https://github.com/typehero/typehero/assets/86230182/74c4f034-3e03-4e39-927e-2c53b198e3a1)

![image](https://github.com/typehero/typehero/assets/86230182/55be5a5c-0492-4e9d-ba92-fef54bb1129e)

**Comment by Nkemjikanma** [comment]
Hey man, are you working on this? @MuhammadM1998

**Comment by MuhammadM1998** [comment]
@Nkemjikanma would love to but it's react and I'm a vue dev 😅

**Comment by Nkemjikanma** [comment]
hahaha! @MuhammadM1998 
Vue is really impressive and you look like you kill it. 

Would you mind if I work on this?

**Comment by MuhammadM1998** [comment]
@Nkemjikanma Thanks 😁 I think it's up to the maintainers to assign the task but I don't think they would mind if you sent a PR. Good luck!

**Comment by Nkemjikanma** [comment]
Yes yes, sure! @MuhammadM1998 
Was just being sure you weren't working on it already.

**Comment by bautistaaa** [comment]
> hahaha! @MuhammadM1998 Vue is really impressive and you look like you kill it.
> 
> Would you mind if I work on this?

assigned :)

**Comment by Nkemjikanma** [comment]
Hey man, @bautistaaa 
Can we close this issue now?
