### ISSUE TITLE
[Bug]: navigation to /404 throws server side exception

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1185]
### What happened?

appear to be fine on other invalid urls

**Comment by rbrtj** [comment]
It seems like it is working properly locally. After a quick research, it appears that there could be a problem with Vercel variables, but I'm not sure, and I don't really see a way to test it myself.
![image](https://github.com/typehero/typehero/assets/92210485/0244bac6-1a4d-4a00-8d42-1737d5c919bb)

**Comment by bautistaaa** [comment]
> It seems like it is working properly locally. After a quick research, it appears that there could be a problem with Vercel variables, but I'm not sure, and I don't really see a way to test it myself. ![image](https://private-user-images.githubusercontent.com/92210485/286032421-0244bac6-1a4d-4a00-8d42-1737d5c919bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODkyNzMsIm5iZiI6MTcwMTE4ODk3MywicGF0aCI6Ii85MjIxMDQ4NS8yODYwMzI0MjEtMDI0NGJhYzYtMWE0ZC00YTAwLThkNDItMTczN2Q1YzkxOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2MjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODBhMjU4OTRlYzIxNjlmODJjYjEzM2YxYTY5NjQ2NjZlNzhlZWYwZjMzMDhlZmMxODU1NDJmMzBmNTA1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PjlddtbcyEYl2B2BUEhrFekDmOoCoDngocWBYZ2lMGY)

what in the world. ill check sentry logs

**Comment by mdwiltfong** [comment]
I'm seeing this in production as well. @bautistaaa , did Sentry logs reveal anything? Here's an instance if that helps. 

I was wondering if possibly adding a dynamic catch-all route would help here? 

<img width="895" alt="Screenshot 2024-01-06 at 10 45 50 PM" src="https://github.com/typehero/typehero/assets/76107997/52c03584-ec09-4e13-91dc-1120295f235a">


<img width="710" alt="Screenshot 2024-01-06 at 10 40 19 PM" src="https://github.com/typehero/typehero/assets/76107997/a0e6992f-511d-4f88-af86-abf43fa383f3">

**Comment by bautistaaa** [comment]
perhaps? does that fix the issue

**Comment by bautistaaa** [comment]
thought we had a catch all already though

**Comment by mdwiltfong** [comment]
It worked in either case 😂  It sounds like a configuration issue though. It would be interesting to see what the logs say.

**Comment by mdwiltfong** [comment]
I should also mention that I see the 404 page on random paths. It's only at /404 that it throws a server error
