### ISSUE TITLE
[Bug]: styles appear to be leaking into the markdown editor

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1186]
### What happened?

try italics and see the result below. you can do this in your settings

<img width="566" alt="CleanShot 2023-11-26 at 08 47 56@2x" src="https://github.com/typehero/typehero/assets/3660667/e919c332-f1c1-486c-a9a1-c2064be6ae70">

**Comment by me-imfhd** [comment]
looks like its already resolved, working fine here

**Comment by bautistaaa** [comment]
we resolved this by disabling html
