### ISSUE TITLE
[Bug]: Pi-Hole blocks cdn.jsdelivr.net

### ISSUE THREAD

**Issue by WVAviator** [typehero/typehero#1206]
### What happened?

Anyone who uses Pi-Hole to block ads at the network/domain level will not be able to use TypeHero by default unless they whitelist cdn.jsdelivr.net from the Pi-Hole admin dashboard. TypeHero does not inform the user of this - it simply says "Cannot find module 'type-testing' or its corresponding type declarations." and will not accept submissions.

<img width="506" alt="Screenshot 2023-11-29 at 9 07 10 PM" src="https://github.com/typehero/typehero/assets/11326285/6c84b21e-6679-43a9-b9fd-052dedac0efa">

<img width="443" alt="Screenshot 2023-11-29 at 8 55 34 PM" src="https://github.com/typehero/typehero/assets/11326285/2553ff2c-d5c0-4d59-bafe-77b88362b297">

Here is a screenshot from my Pi-Hole admin dashboard showing that it was blocked:

<img width="854" alt="Screenshot 2023-11-29 at 9 00 22 PM" src="https://github.com/typehero/typehero/assets/11326285/bebf5444-28d1-4a32-8b46-b68e006f5cf0">

I recognize that should I choose to block ads, whitelisting domains is my responsibility. Typehero probably shouldn't have to do anything special, like change to a different cdn, just for user like me. I do, however, think that if this one particular error is displayed, perhaps the user could be given a hint about what could be causing it - either through some troubleshooting/faq/documentation on the site, or directly in the editor.

I would recommend a more descriptive message in place of the toast notification that currently reads, "Uh oh! You still have errors." - perhaps if the error detected is coming from the read-only editor instead of the user's editor? Alternatively, detect if the network request to cdn.jsdelivr.net fails, and show a modal for the user.

Should you decide to make any code or documentation changes regarding this, I would love to be the one assigned to it.

### What browsers are you seeing the problem on?

All

**Comment by bautistaaa** [comment]
closing as this should be resolved in the ad blocker being used
