### ISSUE TITLE
Design issue on website.

### ISSUE THREAD

**Issue by raja-OX** [typehero/typehero#1208]
Design issue on bottom right. 

![Screenshot from 2023-11-30 09-37-05](https://github.com/typehero/typehero/assets/112232124/bf6f11a4-dcc2-4d15-85ef-923bbca79975)

**Comment by aakash19here** [comment]
> I have a Mac M2, latest OS. I don't see this issue on Safari or Chrome.

Ohh , I'm on Ventura, and I have this issue on Safari. Not sure that we are using anything that is not supported in firefox.

**Comment by WVAviator** [comment]
I can see it on Firefox 119.0.1 on my mac, but not in any chromium browser.

**Comment by jhechtf** [comment]
Closing as I can't reproduce this anymore
