### ISSUE TITLE
[Bug]: Someone else profile

### ISSUE THREAD

**Issue by fecony** [typehero/typehero#1210]
### What happened?

/Didn't explore repository code/ 

Just joined on website, opened my account and there is someone else 😭 
https://typehero.dev/@Richard
![Screenshot 2023-11-30 at 16 38 23](https://github.com/typehero/typehero/assets/36774784/45118c21-0c52-4241-b7dd-a6ccee8389e4)

Maybe profile pages based on name and not github username is not best idea.

If it's just a placeholder image/profile, then anyway /@username will be unique and not /@name profile url  :eyes:

### What browsers are you seeing the problem on?

All

**Comment by WVAviator** [comment]
I was also just thinking that it'd be nice if I could change my username. I'd rather use my handle @WVAviator than my full name. There does not appear to be an option to do so currently in settings.

**Comment by bautistaaa** [comment]
hmm we use your login, which should be unique `profile.login`

**Comment by bautistaaa** [comment]
> I was also just thinking that it'd be nice if I could change my username. I'd rather use my handle @WVAviator than my full name. There does not appear to be an option to do so currently in settings.

whats your profile url?

**Comment by bautistaaa** [comment]
working on fix @fecony we'll likely need to do some manual stuff for your account and whoever else that is impacted

https://github.com/typehero/typehero/pull/1212

**Comment by fecony** [comment]
> working on fix @fecony we'll likely need to do some manual stuff for your account and whoever else that is impacted
> 
> 
> 
> https://github.com/typehero/typehero/pull/1212
> 
> 

It's has nothing yet so whatever 😄

**Comment by bautistaaa** [comment]
@fecony @WVAviator 

can yall talk in discord so i can try to update your name to your login

**Comment by bautistaaa** [comment]
@fecony 

https://typehero.dev/@fecony

**Comment by fecony** [comment]
@bautistaaa Thank you for fixing this so quickly! ❤️

**Comment by Hacksore** [comment]
@bautistaaa did you commit your fix script anywhere?

**Comment by ishtiaq156** [comment]
> working on fix @fecony we'll likely need to do some manual stuff for your account and whoever else that is impacted
> 
> #1212

looks like I'm impacted as well.
Here's my actual profile link - https://typehero.dev/@Ishtiaq%20Ul%20Haq%20Syed
I would like it to be https://typehero.dev/@ishtiaq156 - which has same handle as GitHub's https://github.com/ishtiaq156

**Comment by bautistaaa** [comment]
> > working on fix @fecony we'll likely need to do some manual stuff for your account and whoever else that is impacted
> > #1212
> 
> looks like I'm impacted as well. Here's my actual profile link - https://typehero.dev/@Ishtiaq%20Ul%20Haq%20Syed I would like it to be https://typehero.dev/@ishtiaq156 - which has same handle as GitHub's https://github.com/ishtiaq156

interesting i thought i fixed this but maybe i missed some people, let me update yours
