### ISSUE TITLE
[Bug]: Session type is incorrect

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1215]
### What happened?

session type should have an optional user property

```ts
 interface Session extends DefaultSession {
    user?: DefaultSession['user'] & {
      id: string;
      role: RoleTypes[];
    };
  }
  ```
  
  code will need to be updated everywhere  after this change is made

**Comment by junsupark94** [comment]
Just need to add the question mark after user in packages/auth/src/react.ts and packages/auth/src/server.ts?

How would I test where the code breaks from this change? I ran `npm run lint` and it came back empty.

**Comment by bautistaaa** [comment]
> Just need to add the question mark after user in packages/auth/src/react.ts and packages/auth/src/server.ts?
> 
> How would I test where the code breaks from this change? I ran `npm run lint` and it came back empty.

run pnpm checks:fix or pnpm typecheck
