### ISSUE TITLE
[Feature]: Have the Submit button say Login to Submit when not authed for advent of typescript

### ISSUE THREAD

**Issue by RhysSullivan** [typehero/typehero#1216]
### Description

![image](https://github.com/typehero/typehero/assets/39114868/2a5d707f-cbd6-43b6-a87e-ff35d7530d5b)

### Explanation

This tells the user how to solve the problem without them having to wait for the popup to load

**Comment by paradoxloop** [comment]
+1 this confused me for about 5 minutes before I tried logging in to enable the submit button
