### ISSUE TITLE
[Feature]: Show tab content correctly when navigating tabs with a keyboard

### ISSUE THREAD

**Issue by andrewmcoupe** [typehero/typehero#1219]
### Description

When navigating with a keyboard, pressing left and right on the tab list should render the correct tab content but this only happens upon pressing Enter when a tab is focused.

https://github.com/typehero/typehero/assets/24691226/47509bdb-0160-46cd-a8ab-7d3679bbe6e0

### Explanation

This allows the user to navigate via keyboard with expected results in the context of using tab components.

**Comment by junsupark94** [comment]
Here is my PR https://github.com/typehero/typehero/pull/1228. Let me know what you think.

**Comment by bautistaaa** [comment]
is that typical behavior to auto click on arrow keys? do you have an example of this?

**Comment by junsupark94** [comment]
I don't know, I didn't look into that. My bad.

I just saw that the TabsContent is controlled by pathname and clicking on the TabsTrigger uses router to update the path. So I made the focus event also trigger the click, but I can change it to also use the router to update the path just like the click event.

**Comment by andrewmcoupe** [comment]
> is that typical behavior to auto click on arrow keys? do you have an example of this?

Yep, see guidelines below. Strange, as Radix implements this out of the box.

https://www.w3.org/WAI/ARIA/apg/patterns/tabs/

> When focus is on a tab element in a horizontal tab list:
> Left Arrow: moves focus to the previous tab. If focus is on the first tab, moves focus to the last tab. Optionally, activates the newly focused tab (See note below).
> Right Arrow: Moves focus to the next tab. If focus is on the last tab element, moves focus to the first tab. Optionally, activates the newly focused tab

**Comment by junsupark94** [comment]
Ahh you meant in regards to a11y principles. I'll make sure to refer to those in the future.

Radix does have it on by default because the TabsContent is uncontrolled by default. Here it's controlled.

**Comment by odicho** [comment]
Looks like this has been fixed, so I'll go ahead and close the issue!
