### ISSUE TITLE
Login To Submit button is disabled

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [typehero/typehero#1229]
![image](https://github.com/typehero/typehero/assets/31078314/ae954138-5c1d-404b-877f-1a1a7bf2e5fa)

**Comment by bautistaaa** [comment]
because you have to login top right 😅 (you're not logged in)

**Comment by PeterKwesiAnsah** [comment]
So basically button is telling me to look for the login page instead of allowing me to login directly😅??

**Comment by bautistaaa** [comment]
> So basically button is telling me to look for the login page instead of allowing me to login directly😅??

yeah i can see the angle but now that you know just click the login button up top. id also recommend not using mobile if possible
