### ISSUE TITLE
[Feature]: Show completed and total challenges per Difficulty on Explore page.

### ISSUE THREAD

**Issue by raulrusu88** [typehero/typehero#1240]
### Description

In Explore, we have each Difficulty row with it's challenges, you can see which one you've completed out of the six (cards) that are shown in the page, but what if you want to see how far are you from completing the whole challenge for that particular Difficulty?
I had this idea, while I finished the Track for Beginners, and I went to explore, and I thought I was not finished with "Basics" challenges, even though I were, there's where the idea came from.

We show how many completed out of the total of challenges per difficulty, and if finished, we show the Checkmark.
<img width="1492" alt="Screenshot 2023-12-02 at 18 24 04" src="https://github.com/typehero/typehero/assets/10065009/7114b730-2680-4807-b0bc-6dabd6821d1d">

<img width="1489" alt="Screenshot 2023-12-02 at 18 24 14" src="https://github.com/typehero/typehero/assets/10065009/d04049d9-c2cf-4bee-9c94-fc23e5249e31">

FYI: Code is completed, but according to the CONTRIBUTING.md, we must open an issue first, and I haven't done that out of excitement.

**Comment by bautistaaa** [comment]
ohh i like this however its not very clear that the number represents number of solved. this information is available on your profile and curious if thats enough for now

cc @ayrock-dev @zaCKoZAck0

**Comment by odicho** [comment]
I think this is a great idea! I also am not sure of whether the information in profile is sufficient for the purpose of knowing whether you completed a level of difficulty or not, but I think the checkmark in each card as a visual indicator that this particular challenge has been completed is very nice UX!

**Comment by raulrusu88** [comment]
So I made screenshots with all the possibilities that @odicho said.

The last one with percentages is cool, but is not as explicit, if I put it correctly, but I might be wrong.
Personally I would go with the 3rd one, but at the same time, between `Solved` and `Completed`, I believe we need to see what impact the word has to the User. 

`Solved` - Take problem and figure it out and solve it (Has more of an impact??? maybe I'm reading to much into it)
`Completed` - When you take a task and finish it (More underwhelming???)


1. ![Screenshot 2023-12-12 at 08 00 59](https://github.com/typehero/typehero/assets/10065009/8f3c86c1-1050-495b-839e-08fb529782eb)
2. ![Screenshot 2023-12-12 at 08 01 22](https://github.com/typehero/typehero/assets/10065009/334ce06f-e737-4df8-bbbc-4f1551593002)
3. ![Screenshot 2023-12-12 at 08 01 38](https://github.com/typehero/typehero/assets/10065009/03c75023-6c94-45d2-b55f-0307f42f2133)
4. ![Screenshot 2023-12-12 at 08 01 54](https://github.com/typehero/typehero/assets/10065009/666ab380-8bd3-4dde-8250-a3a488e18ea6)
5. ![Screenshot 2023-12-12 at 08 04 28](https://github.com/typehero/typehero/assets/10065009/6e603f9a-ef78-49bf-a78e-dc36704e1dd8)

**Comment by odicho** [comment]
Nice work!!

I agree with you, I think 3. looks pretty nice! It reflects the meaning of the number, and it also gives an indicator of how many problems are left, exactly the amount of information is needed. I also think solved is more appropriate as well, just due to the nature that these are all puzzles/problems/challenges that needs to be `solved`. Also we stay consistent with the wording of submitting solutions and solutions in the profile page as well!
