### ISSUE TITLE
[Feature]: Return to /explore/[challenge type] after submitting a challenge solution

### ISSUE THREAD

**Issue by Sang-Dang** [typehero/typehero#1242]
### Description

![image](https://github.com/typehero/typehero/assets/92671777/368a79c4-f3c4-4b03-8af9-f5f24b3de943)
There should be a button on this screen or on the main challenge details page to return directly to the /explore/[challenge type] instead of going explore -> view more

**Comment by zaCKoZAck0** [comment]
It should probably show suggestions, on a successful submission.
