### ISSUE TITLE
[Bug]: Two slash plugin don't work correctly

### ISSUE THREAD

**Issue by duckhoa-uit** [typehero/typehero#1244]
### What happened?

The two-slash plugin in the Monaco editor doesn't work correctly. When visiting different challenges, it shows types in a random line.

It requires refreshing to work correctly.

**Reproduce**
1. Visit the day 1 challenge
2. Submit Answer
3. Visit day 2 
4. The two-slash in the editor shows the result in the random line

https://github.com/typehero/typehero/assets/54369632/6975c7ef-ccc3-4300-8048-3f9403330d80

### What browsers are you seeing the problem on?

Chrome

**Comment by WVAviator** [comment]
Yes exactly.

As far as getting it to completely refresh and not show the incorrect hints at all, I've been researching and trying things to no avail. I can continue to hunt for a fix on that if you want.

**Comment by bautistaaa** [comment]
i think this is good enough for now
