### ISSUE TITLE
[Feature]: Trigger re-render of `CardGrid` component on new day of Advent of Code

### ISSUE THREAD

**Issue by TheMythologist** [typehero/typehero#1245]
### Description

When the countdown timer in `CountdownTimer` component hits 0, trigger a re-render of the `CardGrid` component, thus updating the challenges to include the latest challenge.

I am willing to work on this feature myself and create the PR, is that ok?

### Explanation

Useful for automatic refreshing of challenges to see the new challenge immediately if the site is already open, instead of having the user manually refresh the page.

**Comment by bautistaaa** [comment]
yeah i just saw that 😂

we quickly coded it last night 😅

**Comment by odicho** [comment]
This issue has been fixed already, so I'll close this issue!

For reference, a `router.refresh()` was added because the AotLandingPage is a server component.
