### ISSUE TITLE
[Bug]: Incorrect Information in literal-types challenge.

### ISSUE THREAD

**Issue by dirudeen** [typehero/typehero#1250]
### What happened?

The description of the Literal Types challenge under the beginners section says:

> JavaScript, like most programming languages has a concept of [primitive data types](https://typehero.dev/challenge/primitive-data-types). Primitive data types are things like string, boolean, number, and object.

But object is not a primitive type, it's a non-primitive type in JavaScript. So I guess object should be replace with Null, Undefined, BigInt or Symbol.

![Screenshot 2023-12-03 at 15-19-15 Literal Types TypeHero](https://github.com/typehero/typehero/assets/93408077/d204bd4d-2c91-439c-8da2-c730f68eb420)

**Comment by and-kushnir** [comment]
Hello!
You can assign it to me

**Comment by bautistaaa** [comment]
resolved
