### ISSUE TITLE
[Feature]: Showing Top load bar between page transitions, for showing page loading progress

### ISSUE THREAD

**Issue by SRX9** [typehero/typehero#1267]
### Description

- While using TypeHero WebApp sometimes initially, when switching between pages, it takes more than 1 or 2 seconds so user can be in doubt if the click worked or not. 
- This feature introduces a simple top load bar that appears during page transitions, enhancing the user experience by visually indicating progress. 
- The color and style of the bar will be customizable but will have a default setting that matches the application's design aesthetics.

![image](https://github.com/typehero/typehero/assets/46242040/cddfe591-f7ef-497e-82bf-0bcb868c4f39)

### Explanation

I've used this in other live projects (ayedot.com for example), and it works really good for user experience.

**Comment by bautistaaa** [comment]
each route should a loading tsx file accompanied by it that should be triggering, if it’s not we need to look into why

**Comment by SRX9** [comment]
> each route should have loading tsx file accompanied by it that should be triggering, if it’s not we need to look into why

I understand your point regarding the presence of loading.tsx files for each route, which triggers skeleton loaders. These loaders are indeed functioning as expected. 

- The gap this feature is trying to address, is the initial Page loading phase that occurs immediately after a user action (click to new page) and before the skeleton loaders(of the new page) kick in. 
- In certain scenarios, especially under slower network conditions or when dealing with heavy content, there's a noticeable delay before the loading.tsx skeleton loaders appears as they are not available beforehand everytime as far as i know. 
- So, under such scenarios, during this interval, the user might experience uncertainty about whether their action was registered or not.

**Comment by bautistaaa** [comment]
can you give me an example of the navigation flow. maybe could leverage streaming

**Comment by SRX9** [comment]
> can you give me an example of the navigation flow. maybe could leverage streaming

Mostly the flows containing moving to pages which loads content dynamically, would experience such cases. 
Here is a video with such example:-
- First i try to click on those cards and it took 1+ sec to go to that page after the click.
- Then as you can see when i was on page "Tracks" and moved to "Explore", after click on Explore it took almost 1.5s to see the new page. 

https://github.com/typehero/typehero/assets/46242040/7b0842ed-42d1-474e-a226-c28d5970ccb2

**Comment by bautistaaa** [comment]
understood this is kind of the baggage that comes with server rendered pages. im not a fan of the material like loading bar at the top so its not something I think we will implement but instead should optimize loading times and leverage streaming where possible
