### ISSUE TITLE
[Bug]: When typing in 256 characters within the Profile bio, both the Challenges and Bio section extend out.

### ISSUE THREAD

**Issue by MichaelG824** [typehero/typehero#1280]
### What happened?

Expected: The Challenge/and bio section would stay at a fixed width percentage according to the page. 

<img width="1310" alt="Screenshot 2023-12-07 at 8 57 22 PM" src="https://github.com/typehero/typehero/assets/24363724/99be41cf-24a3-43c5-bda0-5a67bdb6e92f">

Actual: When typing in 256 characters into the Bio, both the Challenges and Bio section extend far out. 

### What browsers are you seeing the problem on?

Google Chrome

**Comment by zaCKoZAck0** [comment]
LGTM, I think we need to break-word on overflow.

**Comment by MichaelG824** [comment]
<img width="866" alt="Screenshot 2023-12-11 at 5 31 08 PM" src="https://github.com/typehero/typehero/assets/24363724/dda9cc5c-32e2-4589-8bed-ab0503327620">
<img width="528" alt="Screenshot 2023-12-11 at 5 31 43 PM" src="https://github.com/typehero/typehero/assets/24363724/82b5e6ae-0dcf-44d9-99de-1eeba4857160">

Looks good on Prod. I'm going to close this issue.
