### ISSUE TITLE
[Feature]: Adding a thumbs down option 

### ISSUE THREAD

**Issue by MichaelG824** [typehero/typehero#1293]
### Description

<img width="497" alt="Screenshot 2023-12-09 at 10 52 11 PM" src="https://github.com/typehero/typehero/assets/24363724/ed989023-1120-4c58-b58b-34213b2613fc">

Maybe here too? 
<img width="582" alt="Screenshot 2023-12-09 at 11 02 29 PM" src="https://github.com/typehero/typehero/assets/24363724/ddab2c80-21d3-4c16-91da-9de8e2cfefd3">

Adding a thumbs down option next to the thumbs up option. 

### Explanation

I think it may help users get a better understanding of which problems are well written and/or more useful to them in their daily workplace and which problems can be written better or misaligned with each of the problem's difficulty level.

**Comment by bautistaaa** [comment]
there will be no downvoting. if they don’t like it they can just not upvote
