### ISSUE TITLE
[Bug]: Website is unresponsive

### ISSUE THREAD

**Issue by imanaspaul** [typehero/typehero#1296]
### What happened?

I just opened the website, and then tried to click on explore tab, nothing happens then tried to open next tab right next to the explore menu, and it went to that page with an skeleton loading screen, after a while I tried to click on login button on the top navigation. then it's showing this 
![image](https://github.com/typehero/typehero/assets/34214453/3ac82307-cf2c-4e2d-9493-3f3dd5bee867)
> Inside the console
![image](https://github.com/typehero/typehero/assets/34214453/03b7efcb-b64a-4e59-bea4-90b7bf2b93c8)

### What browsers are you seeing the problem on?

Firefox

**Comment by bautistaaa** [comment]
is this still happening for you?

**Comment by bautistaaa** [comment]
closing until we can get concrete reproduction steps
