### ISSUE TITLE
[Bug]: Advent of TypeScript Day Ten

### ISSUE THREAD

**Issue by RomanShemelin** [typehero/typehero#1297]
### What happened?

Hi . Is it correct test case?  type test_2_actual should not be false in this case?
type test_2_actual = StreetSuffixTester<'Sugar Lane', 'Drive'>;
type test_2_actual = true
type test_2_expected = false;
type test_2 = Expect<Equal<test_2_expected, test_2_actual>>;

**Comment by the-dijkstra** [comment]
#1299

**Comment by bautistaaa** [comment]
resolved
