### ISSUE TITLE
[Bug]: Dismiss button doesn't dismiss the toast.

### ISSUE THREAD

**Issue by andrewmcoupe** [typehero/typehero#1298]
### What happened?

Dismiss button doesn't dismiss the toast.

<img width="478" alt="Screenshot 2023-12-10 at 06 58 51" src="https://github.com/typehero/typehero/assets/24691226/4e8b2e40-efa4-438b-aa1c-3c5f164d4167">

### What browsers are you seeing the problem on?

Chrome

**Comment by wyMinLwin** [comment]
Is this issue solve?
Cause I want to take care of it

**Comment by zaCKoZAck0** [comment]
It's resolved

> Is this issue solve? Cause I want to take care of it
