### ISSUE TITLE
[Feature]: Need only one menu on Navbar

### ISSUE THREAD

**Issue by zaCKoZAck0** [typehero/typehero#1301]
### What happened?

We currently have two menu(s) on the nav (for mobile) 
1. For Profile
![Screenshot from 2023-12-10 14-11-03](https://github.com/typehero/typehero/assets/69889382/b7b34751-ada0-43c0-ab4a-cc94d7a2fbd1)
3. For Nav Links
![image](https://github.com/typehero/typehero/assets/69889382/f8cbe4b0-a2d7-4e4c-8e87-6b9a8c8a8444)

We need only one menu, having two menus can lead to confusion and is a waste of space.
 
Expected:
1. Put the three links (from profile menu) at the bottom on nav menu.
2. Remove the icons, keep the red color for logout.

**Comment by PraveenShinde3** [comment]
Can you please assign it me? will try to fix it.

**Comment by PraveenShinde3** [comment]
Query : should this change needs to be done only for mobile view screen or for all the screens?

**Comment by zaCKoZAck0** [comment]
Mobile only.
