### ISSUE TITLE
[Bug]: almostPi variable is not within default code for problem: 'Literal Types'

### ISSUE THREAD

**Issue by MichaelG824** [typehero/typehero#1313]
### What happened?

<img width="840" alt="Screenshot 2023-12-11 at 4 49 25 PM" src="https://github.com/typehero/typehero/assets/24363724/ac09164e-88ba-477b-9db6-726210c64937">

The variable almostPi is within the tests but is not within the text editor by default. I think there should be an added variable for almostPi. 

### What browsers are you seeing the problem on?

Chrome

**Comment by bautistaaa** [comment]
this is intended. theres a duplicate in the closed issues somewhere
