### ISSUE TITLE
[Feature]: Same challenge should not appear in the More Challenges list

### ISSUE THREAD

**Issue by brightzoe** [typehero/typehero#1316]
### Description

When a challenge is incomplete, the same challenge appear in the 'More Challenges' . I think identical questions should be filtered out.
![image](https://github.com/typehero/typehero/assets/17716768/076f9d74-fb64-46b4-a0ec-1a45c23cc6a2)

Currently, the current challenge is only filtered out after the challenge is completed.

Also,I would like to know whether challenges are tagged? I think it will be better if the recommended questions were similar or required the same approach for resolution.

By the way, this might be a bit off-topic from this issue, I was thinking about the bookmark feature for challenges,  it would be great if we could assign different tags to the bookmarks

### Explanation

Similar challenges and organize the bookmarks into tags are similar to similar questions and collections in LeetCode.

**Comment by me-imfhd** [comment]
@zaCKoZAck0 can you assign me this issue?
