### ISSUE TITLE
[Feature]: add page querystring to url when user navigating solution

### ISSUE THREAD

**Issue by mdm317** [typehero/typehero#1325]
### Description

add page querystring to url when user navigating solution
like this /challenge/get-return-type/solutions?page=2

### Explanation

After users view a solution on the Solutions page, they can return to the current page they were viewing.

**Comment by mdm317** [comment]
If you think this feature is necessary, can it be assigned to me?

**Comment by zaCKoZAck0** [comment]
That sounds like a nice idea, please do.

**Comment by zaCKoZAck0** [comment]
Q: If I'm not wrong, are you trying to put the page number in the query string, for solutions?

The issue is not clear to me.
