### ISSUE TITLE
[Bug]: Advent day 14 typo in type 

### ISSUE THREAD

**Issue by fecony** [typehero/typehero#1326]
### What happened?

A bug happened!

There is typo in advent day 14, type `DecipherNaughyList` should be `DecipherNaughtyList`

### What browsers are you seeing the problem on?

Chrome

**Comment by TRIPLE-ADE** [comment]
I would like to take up the issue

**Comment by the-dijkstra** [comment]
can confirm

```diff
- type DecipherNaughyList = unknown;
+type DecipherNaughtyList = unknown;
```

**Comment by bautistaaa** [comment]
fixed
