### ISSUE TITLE
[Feature]: Ability to delete account

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1333]
### Description

```
This is what Leetcode says: You can ask to have your account deleted by submitting a request to our support team. Please note that this action cannot be undone, so please make sure you have all your data backed up before sending the request.
```

**Comment by Dun-sin** [comment]
How would this be done then? Would it be a pop-up when they click on the delete account button with a form, or will it be an email address?

**Comment by bautistaaa** [comment]
not sure, this isn’t high priority at the moment and just logging it so i don’t forget

**Comment by me-imfhd** [comment]
if i had to add, we can archive accounts and delete it after 60 days so user can recover the account if he wants within those amount of days, i think this is a common practice, but its on maintainers side, i would love to work on this if i get to!! <3
