### ISSUE TITLE
[Feature]: Challenge day 21, tests - NewGame type.

### ISSUE THREAD

**Issue by RauboLuk** [typehero/typehero#1339]
### What happened?

I was working on the challenge for the 21st day and noticed that the type "NewGame" is not inside the test part, but in the playground part and the user can accidentally change it (as I did). I think this can lead to unnecessary errors and this can be moved to the tests section.

### What browsers are you seeing the problem on?

All

**Comment by bautistaaa** [comment]
acceptable for now. well think about this for the next AoT event. thanks for bringing it up (perhaps we can add comments to not modify)
