### ISSUE TITLE
[Feature]: Help study materials for each typescript challenge

### ISSUE THREAD

**Issue by ild0tt0re** [typehero/typehero#1353]
### Description

For each challenge the addition of study materials in order to have the requirements to carry out the challenge independently

### Explanation

As a student I would like to have the opportunity to be guided in understanding what the prerequisites are to be able to do a specific challenge without immediately looking at solutions in case of needs

**Comment by bautistaaa** [comment]
duplicate https://github.com/typehero/typehero/issues/1021
