### ISSUE TITLE
[Feature]: Remember the sorting filter

### ISSUE THREAD

**Issue by g0at1** [typehero/typehero#1367]
### Description

When I change sorting filter then I click on a solution and then go back it changes to default sorting which is "Newest solutions"

https://github.com/typehero/typehero/assets/95431893/0fe1ad1e-7823-451c-9ea7-1f6089ab0923

### Explanation

I'd like my sorting to stay at the value I chose after going back from a solution just like leetcode does.

**Comment by bautistaaa** [comment]
note: add this to local storage for settings probably

**Comment by me-imfhd** [comment]
fixed with local storage
