### ISSUE TITLE
[Feature]: Support Badge

### ISSUE THREAD

**Issue by jiangshanmeta** [typehero/typehero#1372]
### Description

![截图 2023-12-31 11-03-39](https://github.com/typehero/typehero/assets/13798212/84376d74-e27b-4091-b740-90659720f8cd)
support bagde like this

maybe we can add a button in this page . by this button, we can copy badge markdown to clipboard

![截图 2023-12-31 11-08-27](https://github.com/typehero/typehero/assets/13798212/b1ec9fd9-e53a-41c2-9594-24abf4eaa254)

### Explanation

I want to add typehero badge at my github home page so that I can show it to my friends

**Comment by jhechtf** [comment]
I'm down for it. @bautistaaa you got anything against it? 

I'd be down to try and get this going.
