### ISSUE TITLE
[Bug]: Code playground thinks I am not logged in when I actually am.

### ISSUE THREAD

**Issue by weezy20** [typehero/typehero#1396]
### What happened?

I cannot submit code through `explore` or `advent of ts` as the playground thinks that I am not logged in. I tried logging out and then logging back in but to no avail. I am using MS Edge.
![image](https://github.com/typehero/typehero/assets/15669111/e0c3d5bc-fe2c-4967-bdc6-230a433cca7f)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by bautistaaa** [comment]
interesting. can you clear cookies?

also just want to verify it works on other browsers for you

**Comment by weezy20** [comment]
@bautistaaa I just reopened the site (both on chrome and edge) and now it seems to be working fine. Strange because I didn't do anything else. Could close this issue as it's not reproducible.

**Comment by bautistaaa** [comment]
ok feel free to reopen if it happens again
