### ISSUE TITLE
[Chore] May I submit a PR for typo corrections?

### ISSUE THREAD

**Issue by Dann1y** [typehero/typehero#1400]
Hi!

While exploring the Typehero repository, I came across a few typos that I'd like to suggest corrections for. I have forked the repository, and you can review the proposed changes in the pull request I've submitted.

The typos are not critical issues, but addressing them could alleviate potential difficulties in locating specific functions. I believe these corrections will contribute to the overall clarity of the codebase.
(such as `TrackVisibiltyProvider` → `TrackVisibilityProvider`)

I would appreciate it if you could take a moment to review the pull request at your convenience.
https://github.com/Dann1y/typehero/pull/1/files

Thank you :)

**Comment by bautistaaa** [comment]
make a PR to the repo, not your fork
