### ISSUE TITLE
[Bug]: When I want to submit my answer, my answer is wrong (I think I am correct)

### ISSUE THREAD

**Issue by codeusb** [typehero/typehero#1406]
### What happened?

A bug happened!
![image](https://github.com/typehero/typehero/assets/75412910/fe78d119-8870-4133-a832-e2dc384a84b6)

**Comment by swajp** [comment]
Works for me

**Comment by codeusb** [comment]
> Works for me 为我工作

I didn't understand it

**Comment by zmzlois** [comment]
@codeusb 
> > Works for me 为我工作
> 
> I didn't understand it

他的意思是说如果你的回答是对的，你就可以通过，如果答案不对你就不能通过
如果你觉得你的答案是对的但是不通过基本等于你的答案不对

**Comment by jhechtf** [comment]
I can't reproduce this error. Closing for now, re-open if you see it happening again.
