### ISSUE TITLE
[Feature]: keyboard shortcut to submit  a solution

### ISSUE THREAD

**Issue by sital002** [typehero/typehero#1408]
### Description

https://typehero.dev/challenge/default-generic-arguments
User should be able to submit the solution by pressing some keyboard combination. (CTRL + Y)
![image](https://github.com/typehero/typehero/assets/93700622/3b6ec3d5-2b16-409e-98e3-94c5429b0c2b)

**Comment by narutosstudent** [comment]
This would be fun actually

I'd be down to give it a stab

this is also possible on github

cc @bautistaaa

**Comment by bautistaaa** [comment]
> This would be fun actually
> 
> I'd be down to give it a stab
> 
> this is also possible on github
> 
> cc @bautistaaa

sure, there’s already some code you can use as inspiration for “saving” ctrl s
