### ISSUE TITLE
[Bug]: typeof challenge: cannot find name, preventing tests from resolving.

### ISSUE THREAD

**Issue by one2code** [typehero/typehero#1425]
### What happened?

On the typeof lesson, the values being passed into typeof cannot be found, starting with the provided example, `type Width = typeof width;`. Each subsequent typeof returns a cannot be found error, despite satisfying the provided tests in the lesson. Since variables such as width, margin, and d3ChartConfig have been correctly defined, they should resolve correctly. Based on previously submitted answers, it looked like the these values did resolve correctly in the past, and based on the comments, it seems like several other issues experienced the same problem.

When I looked at the logs, I saw an error for an unresolved promise. After reloading the browser, the promise resolved, and the tests had passed (sorry, I wasn't able to capture the log). I haven't be able to replicate the Promise failing, but when it does fail, it prevents the tests from passing. I have both a rejected and accepted submission with the same code that demonstrates this condition when the Promise is unresolved. It is possible that a file like `TrueCases.d.ts`-or other test related files- is occasionally failing to return a 200, leading to the tests being unresolvable. 

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by jhechtf** [comment]
Do you have a link to the actual challenge?

**Comment by LefanTan** [comment]
> Do you have a link to the actual challenge?

Saw the same issue here:
https://typehero.dev/challenge/typeof

**Comment by bautistaaa** [comment]
this is a known bug. typically a refresh resolves it and that's "good enough" for now until we move validation to the server
