### ISSUE TITLE
[Feature]: Show challenges that have not been completed first in their explore page

### ISSUE THREAD

**Issue by ickynavigator** [typehero/typehero#1427]
### Description

On the explore page for a challenge (see [hard](https://typehero.dev/explore/hard)), I would like the challenges that have not been solved to be shown first.
<img width="1237" alt="Screenshot 2024-02-22 140450" src="https://github.com/typehero/typehero/assets/46367335/00036ec0-d919-4dd5-9bf9-1abf38b576d2">

### Explanation

This will help me jump to the new/incomplete challenges quicker since i don't have to scroll through the full page to find whatever i want to work on

**Comment by ickynavigator** [comment]
I would be willing to work on this btw

cc: @bautistaaa

**Comment by jhechtf** [comment]
Assigned to you @ickynavigator , good luck and god speed.

**Comment by ickynavigator** [comment]
@jhechtf just sent in a PR
