### ISSUE TITLE
[Bug]: Typo in the challenge for day 10

### ISSUE THREAD

**Issue by mangoischke** [typehero/typehero#1431]
### What did I find?
The type name for the test and the challenge for day ten don't match.

<img width="798" alt="Bildschirmfoto 2024-03-09 um 00 53 45" src="https://github.com/typehero/typehero/assets/22484446/74bc658c-2805-4844-b488-6be3fb64c60c">
<img width="656" alt="Bildschirmfoto 2024-03-09 um 01 01 16" src="https://github.com/typehero/typehero/assets/22484446/2bb507d2-1b9e-4cdb-86fc-d473c33d8c18">

### Why is this an Issue?
This could be discouraging for any potential user that is confident in their solution but is seeing that the tests fail.

### What could be a potential fix?
Fixing the the typo in by adding the missing "f" in  [this file](https://github.com/typehero/typehero/blob/main/challenges/aot/2023/10/user.ts), transforming `StreetSufixTester` to `StreetSuffixTester` which would then match the tests.

### What browsers are you seeing the problem on?

All

**Comment by mangoischke** [comment]
I would have just created a pull request for such a minor change but under "Your First Code Contribution" it says the following:

> Choose an issue from the [GitHub issues](https://github.com/typehero/typehero/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), ask a member of the team to assign the issue to you.

So, I don't want to break the rule written for everyone.

**Comment by bautistaaa** [comment]
you can fix it :)
