### ISSUE TITLE
[Bug]: Discord link is expired

### ISSUE THREAD

**Issue by prabhatthapa** [typehero/typehero#1438]
### What happened?

Trying to join the Discord channel but link in the README.md shows as expired. Can someone please update it?

### What browsers are you seeing the problem on?

Chrome

**Comment by anshulsoni2010** [comment]
If this is not done yet then please assign me as it's very crucial to get it update ASAP!

**Comment by michael-harvey** [comment]
Seems fine?

**Comment by michael-harvey** [comment]
Your invite might have expired for various reasons, but this seems like it's on the discord side. The invite system is still definitely working for me. 

Try a different browser in incognito and try the link to test it. [discord link](https://discord.gg/trashdev)
