### ISSUE TITLE
[Bug]: TypeScript CDN domain migration

### ISSUE THREAD

**Issue by RyanCavanaugh** [typehero/typehero#1443]
### What happened?

Hi there! We noticed you're using [typescript.azureedge.net in your source code](https://github.com/typehero/typehero/blob/00be144826c5bc373bcc051f753b91798258a280/tooling/scripts/dl-monaco.ts#L10). We're doing a domain migration for our internal CDN content; typescript.azureedge.net is now at playgroundcdn.typescriptlang.org. Please update your URLs as soon as practical.

We're still working out a deprecation schedule but I can update you on that as more information becomes available, if needed.

**Comment by bautistaaa** [comment]
Thanks Ryan!

Should we anticipate any side effects from changes URL's?

**Comment by RyanCavanaugh** [comment]
Nope, everything else should work the same

**Comment by Hacksore** [comment]
GOATED, taking a look at the PR now!
