### ISSUE TITLE
[Bug]: Tests don't run

### ISSUE THREAD

**Issue by Davidcharlie381** [typehero/typehero#1459]
### What happened?

The tests keep failing, and whenever I hover on 
`import { Expect, Equal } from 'type-testing';`
TypeScript yells, saying "Cannot find module 'type-testing' or its corresponding type declarations."

### What browsers are you seeing the problem on?

All

### Relevant log output

```zsh
Cannot find module 'type-testing' or its corresponding type declarations.
```

**Comment by bautistaaa** [comment]
this is known, unfortunately you just have to refresh until we implement server side validation
