### ISSUE TITLE
[Feature]: Notifications

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1477]
### Description

Users should be able to receive notifications when

- someone replies to their comment/solution
- tags them in a comment
- someone likes their comment/solution

We can just poll for the initial version.

**Comment by kfahad5607** [comment]
What kind of notifications we are talking about? Email notifications or in-app notifications or something else? Would love to contribute to this feature.

**Comment by bautistaaa** [comment]
> What kind of notifications we are talking about? Email notifications or in-app notifications or something else? Would love to contribute to this feature.

for the initial version just in app notifications
