### ISSUE TITLE
[Feature]: Profile redesign

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1480]
### Description

Profile has always needed some love. Would like to use the new shadcn charts

**Comment by dca123** [comment]
lfg, i was looking at it and wondering if I should animate those bars, or use one of those fancy shadstuff. Lemme get a mockup on this

**Comment by bautistaaa** [comment]
> lfg, i was looking at it and wondering if I should animate those bars, or use one of those fancy shadstuff. Lemme get a mockup on this

thank god we need this so bad lol
