### ISSUE TITLE
[Feature]: Add a support/subscriber feature

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1496]
### Description

Add a support page/whatever that allows our users to financially support us if they do so. This should enable a new user type (subscriber/supporter?) which enables some sort of badge on their profile + by their name when the comment etc.

- integrates stripe
- implements new user type
- implements badge
- implements flair by username on comments etc

**Comment by zaCKoZAck0** [comment]
Pls Contributor badge too 🥺

**Comment by bautistaaa** [comment]
> Pls Contributor flair too 🥺

for sure

**Comment by dca123** [comment]
Here's a [prototype](https://www.figma.com/proto/p0WaY1Eq8QuD8hF7QML32F/TypeHero?page-id=0%3A1&node-id=1-2&viewport=385%2C-1865%2C0.75&t=LZbWaIwGDwaHqGT5-1&scaling=min-zoom&content-scaling=fixed) of what im thinking. What do y'all think ? 3 pages here, comments, problem page and the profile page. Feel free to leave comments on the design itself !

Should we use a generic naming convention as Contributor / Donator or something fun like hero and wizard ?

In terms of a flair, im thinking of a generic [badge](https://ui.shadcn.com/docs/components/badge). Another idea i was thinking about was to stylize the text (rainbow, sparkles) and have a mini profile on hover that shows the contributer / supporter status. I'll make another prototype for that in a bit

locations that need flairs that we should keep track of
- /problem/solutions page. 
- /profile
- /problem/solution/comments
- /problem

**Comment by bautistaaa** [comment]
> Here's a [prototype](https://www.figma.com/proto/p0WaY1Eq8QuD8hF7QML32F/TypeHero?page-id=0%3A1&node-id=1-2&viewport=385%2C-1865%2C0.75&t=LZbWaIwGDwaHqGT5-1&scaling=min-zoom&content-scaling=fixed) of what im thinking. In terms of a flair, im thinking of a generic [badge](https://ui.shadcn.com/docs/components/badge). What do y'all think ? 3 pages here, comments, problem page and the profile page. Feel free to leave comments on the design itself !
> 
> 
> 
> Should we use a generic naming convention as Contributor / Donator or something **_fun_** like hero and wizard ?
> 
> 
> 
> Another idea i was thinking about was to stylize the text (rainbow, sparkles) and have a mini profile on hover that shows the contributer / supporter status. [Here](https://www.figma.com/proto/p0WaY1Eq8QuD8hF7QML32F/TypeHero?page-id=6%3A288&node-id=6-291&viewport=952%2C980%2C1.2&t=9uufl9wFrs79SH2a-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6%3A291) is the figma for that. 
> 
> 
> 
> The UX isn't as obvious in 2, but it has a unique look to it and would naturally cause a person to hover over that profile, and make the instant connection when they see the badge on their profile. Possible issues with this could be that it wouldn't play well with screen readers.  
> 
> 
> 
> 
> 
> locations that need flairs that we should keep track of
> 
> - /problem/solutions page. 
> 
> - /profile
> 
> - /problem/solution/comments
> 
> - /problem
> 
> 
> 
> 

this is great! main concern around multiple badges. some people will have 2-4 at times. what do you think?

on the problem author section maybe we leave out the text cause it's so cramped or newline?

**Comment by dca123** [comment]
Great call out on multiple flairs. Do you've examples of what other flairs users might have ? I wanted to clarify between flairs (as in the prototype) vs badges (the existing medals you get for achievements)


>> on the problem author section maybe we leave out the text cause it's so cramped or newline?
yeah, i tried new lining it, but then it visually conflicts with the beginner label below.

**Comment by dca123** [comment]
What do you think about the 'coloured text' option ? It was a random idea, but i'm leaning a bit towards it. It simplifies the design, is visually striking and retro while being a bit different (but not too different) from other websites and doesn't clutter up the UI. It solves the issue of having multiple flairs since we can include it all in the mini profile.

This way, we could also add thread specific flairs, i.e 'OP', 'Solution Author' or 'Problem Author' so that people have better context as they read the thread.

Take a look at this updated [UI](https://www.figma.com/proto/p0WaY1Eq8QuD8hF7QML32F/TypeHero?page-id=6%3A288&node-id=6-291&viewport=689%2C561%2C0.65&t=QH2v8FWDTQnStBhp-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6%3A291)

**Comment by bautistaaa** [comment]
sorry was on my phone and I think I may have fkd up some terminology.

Badges:
- Advent of Typescript 2023 (these exist now). we actually give 4 for the event. example here: https://typehero.dev/@satohshi
- Advent of Typescript 2024

Maybe we only do badges for this event for now but that would make 8 if the accomplished 2024 Advent of Typescript

Flair:
Contributor
Subscriber
Admin/Moderator
more TBD

I actually really like the colored text with hover. Potential downside is its an extra step to see flair/badges. Perhaps we can just limit the number of flair/badges shown? I don't feel strongly here though

**Comment by bautistaaa** [comment]
@dca123 lets continue on this issue https://github.com/typehero/typehero/issues/1509

**Comment by bautistaaa** [comment]
base functionality is in prod
