### ISSUE TITLE
[Bug]: Deletion of Last Comment Results in Prisma Error During Paginated Comments Fetch

### ISSUE THREAD

**Issue by kfahad5607** [typehero/typehero#1504]
## Description

After deleting the last remaining comment of a solution (**i.e., the final comment left, not the last one in order**), we re-fetch the paginated comments with the `page` parameter value set to 0, which causes a Prisma error on the server.

## Reproduction of Error

1. **Delete the last remaining comment of a solution**

   ![Delete Comment](https://github.com/user-attachments/assets/4bebc2f5-3fc8-45e7-a48e-c1577b97c535)

2. **Client fetches paginated comments but the request fails**

   ![Fetch Comments Error](https://github.com/user-attachments/assets/b90086b9-c002-4bba-bdd2-6f5873827702)

3. **The request fails because the `page` parameter value sent to the server is 0**

   ![Page Parameter Issue](https://github.com/user-attachments/assets/dd6cb0f1-1a29-4332-b49a-351b064e9b86)

4. **The `page` parameter being 0 causes the value of the `skip` parameter to be negative, resulting in a Prisma error**

   ![Prisma Error](https://github.com/user-attachments/assets/41f3a7cf-5aee-44fb-995f-0550bb286a43)

   ![Prisma Error Details](https://github.com/user-attachments/assets/9f47f1f4-66f4-4f92-9143-1e4802bc1d89)

## Probable Solutions

1. Add a check on the client to avoid sending invalid `page` values.
2. Add a check on the server to handle invalid `page` values.
3. Checks on both the client and server.

**PS:** I would be more than happy to work on this issue. Please assign it to me if possible.

### What browsers are you seeing the problem on?

All

### Relevant log output

```zsh
web:dev: Error in query graph construction: AssertionError("Invalid value for skip argument: Value can only be positive, found: -10")
web:dev:     at async getPaginatedComments (./src/app/challenge/_components/comments/getCommentRouteData.ts:113:22)
web:dev: digest: "2517259583"
web:dev:  POST /challenge/hello-world/solutions/51 500 in 107ms
web:dev: prisma:error 
web:dev: Invalid `prisma.comment.findMany()` invocation:
```

**Comment by bautistaaa** [comment]
great find! i'll assign you :)
