### ISSUE TITLE
[Feature]: show github profile picture on navbar

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#1520]
### Description

tldr change the little dude icon into the users github profile icon
![image](https://github.com/user-attachments/assets/9ea68714-7be8-4b4f-bdee-6d98daa94cb9)

like how github shows it in the top right
![image](https://github.com/user-attachments/assets/56cd028c-1c6d-4fd4-a445-ea3ed723cb72)

**Comment by bautistaaa** [comment]
i got it yo
