### ISSUE TITLE
[Bug]: System theme selection not working correctly

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#1541]
### What happened?

when toggling system theme in macOS the editor theme and various other places are not the right color scheme.

https://github.com/user-attachments/assets/bb2a8b31-02c6-4761-9426-bb225949a9fe

**Comment by Hacksore** [comment]
related PR by @nathanroark 
https://github.com/typehero/typehero/pull/1157

**Comment by Hacksore** [comment]
@aakash19here reopening this based onthe comment here https://github.com/typehero/typehero/pull/1542#issuecomment-2325140783.

we need to use `systemTheme` like this which will have light or dark in system mode.
```
const { systemTheme } = useTheme();
```

**Comment by AkshayBandi027** [comment]
Hey @Hacksore !  I think make use of **resolvedTheme** in which the active theme is _system_ then resolvedTheme will be either _dark_ or _light_ depending upon user's system preference. else if the active theme is not _system_ then **resolvedTheme** wil identical to theme .


https://github.com/user-attachments/assets/c713807f-51e4-4a57-8102-cbc5d956d79e
