### ISSUE TITLE
[Feature]: Enhance design on "Add a Solution"

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1553]
### Description

It should say "share your solution" or something more compelling than the current design. Button could look better too.

<img width="1180" alt="CleanShot 2024-09-04 at 23 43 25@2x" src="https://github.com/user-attachments/assets/a49e42e7-2e03-4a3b-b06e-71b70bd143dd">

**Comment by hackastak** [comment]
I can take this one

**Comment by bautistaaa** [comment]
> I can take this one

awesome!
