### ISSUE TITLE
[Feature]: Ability to switch panel placement in a challenge (code on the left, instructions on the right)

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#1596]
### Description

a toggle to swap left panel with the right panel here
<img width="1728" alt="Screenshot 2024-10-20 at 1 10 11 AM" src="https://github.com/user-attachments/assets/0d6e4c5e-d052-4ab3-b078-cf87521af77d">

**Comment by PickleNik** [comment]
# Implementation:
could be as easy as applying flex-row-reverse, would be 'lot cooler tho if they animated on swap
<img width="1728" alt="Screenshot 2024-10-20 at 1 12 07 AM" src="https://github.com/user-attachments/assets/4c75a643-215e-47df-8fc6-45ff487771c5">

**Comment by bautistaaa** [comment]
damn it looks nice on the right

**Comment by 17AnuragMishra** [comment]
We can have one more possible layout to implement but anyway would love to work on this as well. @bautistaaa /assign
