### ISSUE TITLE
[Feature]: Comment actions UI improvement

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#1597]
### Description

Currently looks cluttered, no need to show actions for every comment unless it's group-hovered with group being the entire comment block.
<img width="531" alt="image" src="https://github.com/user-attachments/assets/3ad137fe-341d-4994-bf50-497b24187008">

Also, too much spacing with current placement between comment and it's actions, should be less spacing than between actions and the next comment so that it's clear that actions belong to that comment and not the next one (most of that spacing is dictated by markdown `p` and `h1` tags having bottom margins and paddings, so elements below main content might need a negative margin-top, or we could move actions to the right side of the content (with 1 row like/share for other's comments and 2 row delete/edit like/share for own comments))
<img width="345" alt="Screenshot 2024-10-20 at 1 30 29 AM" src="https://github.com/user-attachments/assets/474de148-8dbc-4052-9461-86536285b33f">
<img width="532" alt="Screenshot 2024-10-20 at 1 31 19 AM" src="https://github.com/user-attachments/assets/2b0737e3-e344-4924-ac0c-e704ebbfdbfe">

**Comment by bautistaaa** [comment]
> /assign

assigned to you

**Comment by nafisreza** [comment]
@bautistaaa I understood the second issue that the spacing between comments and actions needs to be less.
Could you please clarify the first one? Would you like to see the actions only when you hover over a particular comment?

**Comment by PickleNik** [comment]
> @bautistaaa I understood the second issue that the spacing between comments and actions needs to be less. Could you please clarify the first one? Would you like to see the actions only when you hover over a particular comment?

yep, I feel like this is too many buttons to look at 10 times over
<img width="211" alt="Screenshot 2024-10-20 at 2 40 50 PM" src="https://github.com/user-attachments/assets/8047f065-0c9b-4a6c-bade-4ccc253ae82f">
By hide on "group-hover" (in tailwind terms) i meant something like this:

https://github.com/user-attachments/assets/39cc1734-3f62-4d34-a329-f7f09b9562e3


In current placement it wouldn't make sense to hide the entire row because we'll still have the empty space, but if we re-arrange them with share, edit, delete being last, those 3 could be hidden by default, leaving only like and reply, would look cleaner imo.

Brainstorming other placement options, share could be moved to the top row next to date, since I imagine it's not used as often as the other buttons, and with side-by-side placement it would make sense to hide all the buttons by default, and reveal them on hover (except maybe like, although like could probably be kept in the same row as reply count and last edited date) 
<img width="493" alt="Screenshot 2024-10-20 at 3 00 35 PM" src="https://github.com/user-attachments/assets/71fedd4f-0fc9-42bd-bbb0-7080aa16d80b">
flexbox
<img width="506" alt="Screenshot 2024-10-20 at 3 02 19 PM" src="https://github.com/user-attachments/assets/d823cecf-2d95-43a7-82b0-258fd4cc7e3c">
@nafisreza

**Comment by PickleNik** [comment]
Just do what seems better, maybe I'm overcooking with buttons on the side

**Comment by nafisreza** [comment]
Hey @PickleNik , I have done the changes as per our requirement. The buttons looks nice on the side (kinda like discord). Also moved reply on the same line as edit history. The actions are now only displayed when group-hovered on the particular comment.

https://github.com/user-attachments/assets/3b63a787-891c-4d58-9328-4a5d779ab19d

**Comment by PickleNik** [comment]
> 
Nice, I think the like button (and probably the share button too since they are on the same line) should be kept visible by default.

It'd be cool if the rest had a staggered reveal transition, if we do a `group-hover` on each of the buttons rather than their container and add different `delay`s on each, that could work I think :)

**Comment by nafisreza** [comment]
Great idea. Take a look. 

https://github.com/user-attachments/assets/998e0be0-366e-4c16-bdc9-bfd52dde0d40

**Comment by nafisreza** [comment]
@bautistaaa I think it looks okay maybe. If you suggest all actions to be visible by default, I can also do that.

**Comment by bautistaaa** [comment]
> @bautistaaa I think it looks okay maybe. If you suggest all actions to be visible by default, I can also do that. 

it's probably fine, maybe instead of share next to the like count it's the reply button? and you can move share to the hidden ones

**Comment by nafisreza** [comment]
I was also thinking the same @bautistaaa. I have moved reply to the top and pushed the changes.

https://github.com/user-attachments/assets/6e4210f0-9e16-421c-bfdb-465f2ea43017
