### ISSUE TITLE
[Bug]: The fallback for user avatar flashes before the real avatar loads

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1607]
### What happened?

fallback avatar should only display after we have confirmed the user is not logged in

### Relevant log output

```zsh
To reproduce you can login and just refresh the home page and look at your avatar top right.

This can also be observed anywhere you see a user avatar since its reused
```

**Comment by Oabanjo01** [comment]
Hi, good morning. Looking to contribute to my first open source project for Hacktober fest. Can this issue be assigned to me?

**Comment by bautistaaa** [comment]
> Hi, good morning. Looking to contribute to my first open source project for Hacktober fest. Can this issue be assigned to me?

sounds good!
