### ISSUE TITLE
[Bug]: Cursorthing on Website

### ISSUE THREAD

**Issue by maxwell-kalin** [typehero/typehero#1611]
### What happened?

A Ghost appears on the Website, had to use a custom filter to remove it.

Annoys the crap out of users.

### What browsers are you seeing the problem on?

All

**Comment by PickleNik** [comment]
![sadghost](https://github.com/user-attachments/assets/79d67dd3-3ed4-48c6-b47d-24c33ca521fa)

**Comment by PickleNik** [comment]
it will fly away after halloweekend
