### ISSUE TITLE
[Feature]: Need designs for AOT 2024 Badges

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1612]
### Description

Would like to implement some new designs for the AOT badges for 2024

Last year:
![CleanShot 2024-10-29 at 14 06 42](https://github.com/user-attachments/assets/081bdf21-14d8-42bf-a2d9-4ca5efdf8140)

We could be lazy and just change to 2024 but lets not 🤣

**Comment by amhitt** [comment]
@bautistaaa Hi, Is the AOT badge design for 2024 still needed? If yes, what format should the designs be provided? 
Thank you!

**Comment by bautistaaa** [comment]
> @bautistaaa Hi, Is the AOT badge design for 2024 still needed? If yes, what format should the designs be provided? 
> 
> Thank you!

sorry we finished it! i'll close the issue
