### ISSUE TITLE
[Feature]: Comment Section UI Improvement needed.

### ISSUE THREAD

**Issue by 17AnuragMishra** [typehero/typehero#1629]
### Description

Following up on #1615, it's somewhat awkward when looking at this picture because there are several aspects, from my point of view, that need attention:

1. The gap between the two comments seems excessive.
2. The "edited" label is not ideally placed; instead, it should be a small label next to the name. The edit details should only be displayed on hover, as its current position interrupts the conversation.
![image](https://github.com/user-attachments/assets/0217957a-e5ec-4579-ae11-20f3cdc76fd1)

**Comment by aquibbaig** [comment]
+1 on this, I too feel that the comments section UX can be improved here.

I have a list of suggestions (also mentioned in https://github.com/typehero/typehero/issues/1615#issuecomment-2455482730)

- moving edit, share and delete to an "actions dropdown". (possibly rename "Share" -> "Copy link"). This will reduce extra space from each comment.
- likes and reply button moved right below the comment (& truncated to some length)
- moving "Last edited" text to the side of the username & displaying it in relative time (2d ago)
- removing unnecessary gaps in between original comment and subsequent text boxes.

I think keeping everything left aligned looks much cleaner.

@bautistaaa I can pick up on the refactor based on the above discussion points and if others have any suggestions. Here's a quick prototype of roughly how it'll look after the changes.

<img width="853" alt="prototype" src="https://github.com/user-attachments/assets/0b12eb14-8321-4256-a828-3ab118e0ac65">

**Comment by satishkumarsajjan** [comment]
Since we are talking about big changes. Should I add feature where users can reply to the comments of comments? A tree of comments just like in REDDIT ?

**Comment by satishkumarsajjan** [comment]
> > Since we are talking about big changes. Should I add feature where users can reply to the comments of comments? A tree of comments just like in REDDIT ?
> 
> Yes, it's somewhat like that. It makes sense because people often engage in conversations in the reply section. If you have any relevant images, please include them before submitting a pull request to avoid creating too many commits in the PR.

got it.

**Comment by sauravk58** [comment]
@bautistaaa please assign me this

**Comment by bautistaaa** [comment]
> @bautistaaa please assign me this

this is already being addressed

**Comment by satishkumarsajjan** [comment]
Made some changes due to conflicts. Closing the previous pull request.
