### ISSUE TITLE
[Bug]: Advent of Typescript type-testing package is not found, no tests run. "Cannot find module 'type-testing' or its corresponding type declarations."

### ISSUE THREAD

**Issue by illepic** [typehero/typehero#1704]
### What happened?

On Advent of Typescript, No tests run because the `type-testing` module is not found.
![image](https://github.com/user-attachments/assets/aedc523c-4942-4e78-a236-e180220416df)
![image](https://github.com/user-attachments/assets/81635795-6d5e-4977-b756-ed5d4b36ed02)

Note that the following libraries fail to load:
![image](https://github.com/user-attachments/assets/a0138914-988c-4100-b2c8-3e6d664ba677)
```



### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

**Comment by bautistaaa** [comment]
yeah this is an annoying bug.

for now just refresh when you encounter it

**Comment by bautistaaa** [comment]
oh shoot its happening all the time o.O

**Comment by bautistaaa** [comment]
i think jsdelivr is having issues.

its doing it on ts playground too

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAnmApnA3nAogD1QYxgBpsBHAVwEMAbOAXzgDMoIQ4ByJVAWhhQGcYwAHYBzdgG4AUEA

**Comment by bautistaaa** [comment]
https://x.com/typeheroapp/status/1865829220162982306?s=46&t=7R4ANlquTzTEPKHtIKnRmA

**Comment by bautistaaa** [comment]
looks like it back up!

**Comment by illepic** [comment]
We're back up here, thanks!
