### ISSUE TITLE
Submissions should only be viewable by its author 

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1715]
### What happened?

anyone can see a submission by plugging in random ids. it should only be viewable by the author. you have to explicitly share them to be public

**Comment by nickbar01234** [comment]
@bautistaaa seems like a small change to [getChallengeBySubmission](https://github.com/typehero/typehero/blob/88492c2f9f119f563528ebef033ab7120b641f1d/apps/web/src/app/challenge/%5Bslug%5D/submissions/%5B%5B...catchAll%5D%5D/getChallengeSubmissions.ts) - mind if I pick this up?

**Comment by bautistaaa** [comment]
> @bautistaaa seems like a small change to [getChallengeBySubmission](https://github.com/typehero/typehero/blob/88492c2f9f119f563528ebef033ab7120b641f1d/apps/web/src/app/challenge/%5Bslug%5D/submissions/%5B%5B...catchAll%5D%5D/getChallengeSubmissions.ts) - mind if I pick this up?

yeah should be a quick fix! thanks
