### ISSUE TITLE
[comments] make comments linkable

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#215]
- [x] Share UI to copy the comment URL (#235)
- [ ] Nested route `/challenge/<challengeId>/comment/<commentId>` 
- [ ] Loading the nested route performs the correct query and pops open the UI

**Comment by Hacksore** [comment]
Pretty sure @metal-face has abandoned this issue so it's up for grabs.

**Comment by Rand0mLetters** [comment]
anybody working on this? I think I could manage it (I actually started working on it before I realized I should ask)

**Comment by Rand0mLetters** [comment]
what's the status on this? I think @bautistaaa was working on an alternative solution to [this pr](https://github.com/typehero/typehero/pull/603), what's the status on that?
