### ISSUE TITLE
[comments|challenges] use a library to block bad words before submission

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#274]

**Comment by qoobes** [comment]
@bautistaaa if you're not already on this, I'll take it as a first issue. That alright?

**Comment by bautistaaa** [comment]
> @bautistaaa if you're not already on this, I'll take it as a first issue. That alright?

didnt realize it was assigned to me. take it!

**Comment by Rand0mLetters** [comment]
is this being worked on (I ask because qoobes was unassigned, and I can't find a pr for this)? if it's not, I'd like to try my hand at this
