### ISSUE TITLE
[Tracks] Build admin dashboard to manage tracks

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#333]

**Comment by jselmani** [comment]
@bautistaaa I'm interested in getting involved here.  I'm going to be pulling the repo down at some point today and getting set up.  Could you provide any designs or implementation details for this ticket?

**Comment by jselmani** [comment]
Bumping this to hopefully get some eyes on it 👀

**Comment by bautistaaa** [comment]
this is done
