### ISSUE TITLE
[challenges] rank the challenges "fairly"

### ISSUE THREAD

**Issue by is-it-ayush** [typehero/typehero#358]
rank the challenges by using a ranking algo. 
- should be fair i.e. cannot be gamed.
- factor in good signals and bad signals. example,
  - likes, comments and views = good signals
  - reports = bad signals. 
  - modify this to whatever works in building a fair system.
- rank's should be recalculated daily/weekly.
- assign `POPULAR` tag to the top 10 challanges and make them visible on `/explore`'s `Most Popular` section. (use `connectOrCreate` for tags. this is important.)

ask @bautistaaa for more info.

**Comment by ARSHIL1804** [comment]
I can pick it up. @is-it-ayush

**Comment by is-it-ayush** [comment]
(cc) @bautistaaa do we still need this on typehero?

**Comment by bautistaaa** [comment]
we can close this for now. we don’t need this atm
