### ISSUE TITLE
Search Challenges

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#414]
Challenge search by name with difficulty filter?
![image](https://github.com/bautistaaa/typehero/assets/31113245/700f6433-151b-42c6-996d-0cef62e488a5)

**Comment by sameer1612** [comment]
I can take it, do assign it if it is up for grabs. Thanks!

**Comment by bautistaaa** [comment]
> I can take it, do assign it if it is up for grabs. Thanks!

we’re not starting any 2.0 work yet, sorry

**Comment by Mahmoudgalalz** [comment]
Can I join the discussion of Building it ?!
@bautistaaa would like to know how the tasks are stored

**Comment by bautistaaa** [comment]
> Can I join the discussion of Building it ?! @bautistaaa would like to know how the tasks are stored

can discuss in the discord
