### ISSUE TITLE
New Tracks UI

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#503]
<img width="906" alt="Screenshot 2023-08-29 at 9 59 28 AM" src="https://github.com/bautistaaa/typehero/assets/31113245/420ee2d1-1d07-487d-800a-e58cd482a36a">

**Comment by falcon-head** [comment]
<img width="1256" alt="image" src="https://github.com/typehero/typehero/assets/32938743/acd38544-eda2-4641-b113-c69d1d8e3b2c">


@PickleNik Above UI needs to be changed to the one you mentioned ?

**Comment by SubxX** [comment]
I can take this task, do we have a design for this or should I create an design like the image @PickleNik provided @bautistaaa

**Comment by bautistaaa** [comment]
> I can take this task, do we have a design for this or should I create an design like the image @PickleNik provided @bautistaaa

we don’t but you can use what leetcode does as some sort of guidance. i don’t think we’ll have images for each track so use your best judgement here

**Comment by SubxX** [comment]
![Explore Tracks _ TypeHero](https://github.com/typehero/typehero/assets/51792949/fd55b908-9e84-439e-ac5e-fb2e36364613)

Need feedbacks @bautistaaa @PickleNik

**Comment by bautistaaa** [comment]
the empty state doesnt need to be so big here. you can probably hide your tracks header.

**Comment by PickleNik** [comment]
I'd get rid of the View button and replace it with "x problems" (or better "x challenges") counter so that the card doesn't take up more space than it needs to

**Comment by PickleNik** [comment]
since there's going to be 6/7 tracks total at launch they could all have a unique design/gradient for the card background

**Comment by SubxX** [comment]
> the empty state doesnt need to be so big here. you can probably hide your tracks header.

You mean hide the whole your tracks section or only the "Your Tracks" heading text if the state is empty

**Comment by SubxX** [comment]
with the gradient and without the icon the card looks to basic TBH so I added a temporary icon  for all the cards that looks good. In future I will make 6/7 icons which will match the track names.

**Here is the final outcome**

![Explore Tracks _ TypeHero (1)](https://github.com/typehero/typehero/assets/51792949/6053c2df-6c12-42c5-99b9-512698ae8746)

Thoughts @bautistaaa @PickleNik

**Comment by PickleNik** [comment]
Lgtm

**Comment by falcon-head** [comment]
Can you share the light mode screenshot as well?

**Comment by SubxX** [comment]
Sure here it is

![Explore Tracks _ TypeHero](https://github.com/typehero/typehero/assets/51792949/509fb0d5-2fd6-45bf-aafd-48b6f8864f14)

**Comment by PickleNik** [comment]
<img width="100" alt="Screenshot 2023-09-10 at 11 16 01 AM" src="https://github.com/typehero/typehero/assets/31113245/96e0c7cb-7f8b-4d57-9206-24deda0cb858">

could the padding be even on all sides pls 🙏

**Comment by PickleNik** [comment]
also I like "Your Tracks" having a different card with the progress bar, it makes sense
