### ISSUE TITLE
[Bug]: The editor hover window doesn't show in the test cases

### ISSUE THREAD

**Issue by ggrandi** [typehero/typehero#506]
<img width="922" alt="image" src="https://github.com/bautistaaa/typehero/assets/49359646/85df216c-332b-4a82-9bcb-4a19ec24b835">

I'm not sure what is causing it but it would be cool to see the hover menus, I know a similar thing happens in the typescript playground

**Comment by oussamaBGZ** [comment]
i just created a PR for this.

**Comment by bautistaaa** [comment]
moving panel to the bottom so non issue
