### ISSUE TITLE
[Feature]: Track detail page

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#512]
### Description

`/tracks/[id]`

needs to be implemented

### Explanation

This page is stubbed out already and you are able to enroll.
We want to take the list UI from `/tracks` and use it here for the list items.

see https://leetcode.com/studyplan/top-interview-150 for inspiration

**Comment by DerTimonius** [comment]
I'd like to help with this one! Any suggestions what the page should look like? I'd guess similar to the `/explore` page

**Comment by bautistaaa** [comment]
> I'd like to help with this one! Any suggestions what the page should look like? I'd guess similar to the `/explore` page

that would be /tracks. this is if you view. specific track

**Comment by Rand0mLetters** [comment]
/tracks/slug? the one that currently has just a title + enroll button?

**Comment by danbadra** [comment]
Hey there! I would also like to help on this one. @DerTimonius do you need any help?
