### ISSUE TITLE
toggle leftPanel width to 0

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#525]
toggle leftPanel width to 0 for maximum editing screen realestate

**Comment by PickleNik** [comment]
being implemented in #523

**Comment by PickleNik** [comment]
//todo: see [/challenge-layout.tsx] TODO for a failed attempt, replace it with working code from #523

**Comment by Tylopilus** [comment]
thoughts on this?
https://jmp.sh/dLnD2c7E
