### ISSUE TITLE
[Feature]: Settings page enhancements 

### ISSUE THREAD

**Issue by kualta** [typehero/typehero#533]
### Description

Improve the overall looks of `/settings` to match the looks of the `/profile` page and display more info.

### Current state 
The design in figma is ready, but it is way ahead of the db schema at the moment. 
Should we mock-up everything for future use and make it throw a not-implemented-yet error toast? 
Should we hold back with it?  Feedback needed.

**Comment by SooditK** [comment]
Hii
I would love to work on this issue.
😄
