### ISSUE TITLE
[Feature]: markdown in challenge cards

### ISSUE THREAD

**Issue by Rand0mLetters** [typehero/typehero#553]
### Description

Instead of rendering backticks, use code bubbles/a monospaced font?
![image](https://github.com/bautistaaa/typehero/assets/108293579/f87f2425-5d9a-44d8-b1cc-6223f39aea17)

PS. I would like to help with this

### Explanation

It looks ugly right now

**Comment by Rand0mLetters** [comment]
Also, crop the card text at the last full word + slap on an ellipsis

**Comment by bautistaaa** [comment]
it’s supposed to be showing a pill


is this using the markdown stuff @Hacksore

**Comment by Hacksore** [comment]
I might have not updated this to use the `<Markdown />`, let me check!

**Comment by bautistaaa** [comment]
https://github.com/bautistaaa/typehero/pull/555
