### ISSUE TITLE
[Bug]: Sentry should only be reporting stagin/prod errors

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#579]
### What happened?

A bug happened!

**Comment by Hacksore** [comment]
You sure we don't want sentry only in prod?

**Comment by bautistaaa** [comment]
> You sure we don't want sentry only in prod?

we have no prod traffic atm. 

plus it’s a sponsored plan so i’m okay with logging multiple envs and it filters nicely based on env i think

if it gets too noisy we can eventually remove it but prod would so no purpose atm since it’s all turned off

**Comment by Hacksore** [comment]
But it's already only showing errors and fatals on localhost?

![image](https://github.com/typehero/typehero/assets/996134/2518a2b8-ae49-44a5-9a45-822f47f0b40a)

**Comment by bautistaaa** [comment]
i totally typod the PR title

**Comment by Hacksore** [comment]
lmao! so we need a regex to capture:
- `staging.typeheo.dev`
- `*.vercel.app`

**Comment by Hacksore** [comment]
![image](https://github.com/typehero/typehero/assets/996134/8a585d1a-aa26-4cdb-a353-b98f6b3303e3)

This was not fixed, still getting localhost.

**Comment by bautistaaa** [comment]
from an up to date branch? branches not rebased will still do it

**Comment by Hacksore** [comment]
> from an up to date branch? branches not rebased will still do it

wait good call, maybe I'm actually wrong.

**Comment by Tylopilus** [comment]
Does it work as expected?

**Comment by bautistaaa** [comment]
> Does it work as expected?

still getting local erros
