### ISSUE TITLE
[Feature]: Sort on /explore/slug

### ISSUE THREAD

**Issue by Rand0mLetters** [typehero/typehero#588]
### Description

Add a "sort by" (newest, easiest, hardest, most popular) UI on /explore/slug

Somewhat redundant (like, /explore/newest + sort by newest?) but I think it has use cases (like, /explore/popular + sort by easiest)

### Explanation

![image](https://github.com/typehero/typehero/assets/108293579/00035147-7671-4f2e-9e25-72ed72479543)

**Comment by bautistaaa** [comment]
I dont think we need this because it is redundant like you pointed out. Maybe once we get a good amount of content we can revisit
