### ISSUE TITLE
implement the new below UI instead of hiding the panel completely

### ISSUE THREAD

**Issue by is-it-ayush** [typehero/typehero#589]
- [x] (optional) show navigation tab buttons even when the panel is collapsed, the should indicate which subroute you're on and un-collapse the page and navigate to the right subroute when clicked

**Comment by bautistaaa** [comment]
what does this mean?

**Comment by bautistaaa** [comment]
oh i see https://github.com/typehero/typehero/issues/585

**Comment by is-it-ayush** [comment]
> oh i see https://github.com/typehero/typehero/issues/585

we makin a sidebar ✨

**Comment by odicho** [comment]
@bautistaaa this should be closed!

**Comment by is-it-ayush** [comment]
@odicho, thank amanuel! i'm closing this. : D
