### ISSUE TITLE
get-rid of icons imported from lucide-react & re-export icons from @repo/ui/icons instead

### ISSUE THREAD

**Issue by is-it-ayush** [typehero/typehero#590]
The following places still import icons from `lucide-react`. You can,
- [ ] re-export them from `@repo/ui/icons` i.e. `./packages/ui/src/icons` & replace them accordingly in the web app.
- [ ] get rid of `lucide-react` dependency from `./apps/web/package.json` to prevent direct imports in future.

![image](https://github.com/typehero/typehero/assets/36449128/94a25fb1-be87-4005-aed3-62eaae6b0033)

**Comment by SubxX** [comment]
I can work on this @is-it-ayush @bautistaaa

**Comment by is-it-ayush** [comment]
@SubxX goodluck! i'm assigning you.

**Comment by is-it-ayush** [comment]
Thank you for contributing @SubxX! I'm closing this issue.
