### ISSUE TITLE
[Bug]: Input field is losing focus

### ISSUE THREAD

**Issue by falcon-head** [typehero/typehero#612]
### What happened?

In the comment section, as soon as I start typing, the input field loses its focus

https://github.com/typehero/typehero/assets/32938743/e9f2bfe1-e42a-4c18-8b15-d7390e2e589a

### What browsers are you seeing the problem on?

All

**Comment by danbadra** [comment]
Hey there! Can I get this issue @bautistaaa?

**Comment by danbadra** [comment]
**Relevant log output**

The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by jproberson** [comment]
@danbadra I had done some minor digging a couple days ago and noticed this seemed to happen for me after this commit:
c130ce7 - feat: integrate million js automatic mode (#430)
Hopefully that will help pin something down.

**Comment by bautistaaa** [comment]
i tested on earlier commits and it was still happening. will try to pinpoint it

**Comment by danbadra** [comment]
Apparently this is a CSS async problem:

https://stackoverflow.com/questions/76219016/how-to-fix-link-preload-warning-in-next-js-app

I tried inserting rel="preload" and as="style" @ index.ts, but it didn't work. I'll keep searching for more solutions.

**Comment by danbadra** [comment]
It seems this bug is also related to Next.js:

https://github.com/vercel/next.js/discussions/49607

**Comment by bautistaaa** [comment]
million ignore worked! making PR now
