### ISSUE TITLE
[Feature]: Make collapsible test panel resizable

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#618]
### Description

see https://leetcode.com/problems/split-linked-list-in-parts/?envType=daily-question&envId=2023-09-06 for an example

**Comment by vivekKumarSinghH** [comment]
Hi @bautistaaa, please assign this issue to me. I have completed the RCA for this issue.

We can hide the left div when resizing below a certain width, as the minimum width of the left side is currently set to 500 pixels

**Comment by bautistaaa** [comment]
this is for the test panel. not the left panel which already collapses

**Comment by danbadra** [comment]
Since the comment input bug was fixed, I can work on this one!

**Comment by michelettoluca** [comment]
Does this look good? 
![image](https://github.com/typehero/typehero/assets/74112450/8356f756-8541-47d3-9b4a-2bad8f0060f2)

**Comment by bautistaaa** [comment]
> Does this look good? ![image](https://user-images.githubusercontent.com/74112450/266756886-8356f756-8541-47d3-9b4a-2bad8f0060f2.png)

looks pretty good! should only be visible when tests is expanded like on leetcode(just clarifying that part!) could you also add a border to the bottom action bar like the header is?

**Comment by michelettoluca** [comment]
Can I get this assigned? I'll open a PR tomorrow
