### ISSUE TITLE
[Feature]: Add tool tip for reset code button

### ISSUE THREAD

**Issue by falcon-head** [typehero/typehero#622]
### Description

I've noticed that the reset button in the challenge editor does not have a tooltip. Thought it would maintain some consistency.

### Explanation

The tooltip is present in the leet code editor. Hence suggesting a change!

**Comment by falcon-head** [comment]
@PickleNik @bautistaaa

**Comment by falcon-head** [comment]
<img width="1383" alt="Screenshot 2023-09-06 at 6 27 51 PM" src="https://github.com/typehero/typehero/assets/32938743/14527f0f-c5e1-49d3-be51-c4a52d341eac">

Something like this may be?

**Comment by PickleNik** [comment]
It'd be lot cooler if it was on the left instead of on the top

**Comment by PickleNik** [comment]
But since on other buttons that would cover the buttons to the left of it i think that's LTMG

**Comment by PickleNik** [comment]
Wait that's an issue, thought this was a PR, was looking for the approbe button

**Comment by falcon-head** [comment]
Haha! Gotta follow the new PR rules :) Let me make a change!
