### ISSUE TITLE
[Feature]: facelift for profile page

### ISSUE THREAD

**Issue by Parthvsquare** [typehero/typehero#625]
### Description

<img width="1137" alt="image" src="https://github.com/typehero/typehero/assets/26404957/47af0209-6326-4729-bd90-e2c85e75eeca">
Updating UI according to figma for profile page. 
1. For pro users adding a crown
2. For non pro simple circle

**Comment by Parthvsquare** [comment]
@bautistaaa can i work on this?

**Comment by Parthvsquare** [comment]
Current Draft

<img width="1513" alt="image" src="https://github.com/typehero/typehero/assets/26404957/a6bd1cf1-8944-4012-ab4a-9ebd512c7199">

<img width="1513" alt="image" src="https://github.com/typehero/typehero/assets/26404957/426d4b5e-e886-411d-b256-e6f98520ec06">

<img width="1513" alt="image" src="https://github.com/typehero/typehero/assets/26404957/d9cdbbef-1d6e-47b2-9d74-6d6a525514a6">

**Comment by basokant** [comment]
@Parthvsquare Looking good so far! There are some weird spacing things that we can fix when we're actually building it out (ex. social links spaced evenly on the vertical axis)

Also, are you planning to facelift all tabs on this page (in-progress, solutions, bookmarks, comments, etc.)? I know the settings page has been touched already.

**Comment by Parthvsquare** [comment]
@basokant will fix the issues.

i was not planning to facelift all tabs, but if i get designs for it i can

**Comment by Hacksore** [comment]
Since we merged the new profile design I am going to close.
