### ISSUE TITLE
[Bug]: Settings page not found.

### ISSUE THREAD

**Issue by falcon-head** [typehero/typehero#630]
### What happened?

Settings page is missing. When I clicked on the settings button under my profile it redirected me to a 404 page

<img width="1436" alt="image" src="https://github.com/typehero/typehero/assets/32938743/8dfa06c0-e8ef-453a-9e53-3bf7ef693dae">

### What browsers are you seeing the problem on?

All

### Relevant log output
<img width="961" alt="image" src="https://github.com/typehero/typehero/assets/32938743/31558ec6-10bc-475f-a3b8-950447c5584c">

**Comment by falcon-head** [comment]
![image](https://github.com/typehero/typehero/assets/32938743/7205fbc7-4b04-4f8b-8e80-274bbda79ce9)

**Comment by Milind-Jamnekar** [comment]
@bautistaaa I got this!
