### ISSUE TITLE
[Feature]: Move us to bun

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#636]
### Description

bleed irresponsibly

### Explanation

we're bleeding edge

**Comment by Alekzv9** [comment]
LGTM

**Comment by PickleNik** [comment]
<img width="398" alt="Screenshot 2023-09-08 at 7 12 42 PM" src="https://github.com/typehero/typehero/assets/31113245/8475cd97-2382-4ae2-8ff1-b43bf595f116">

**Comment by Hacksore** [comment]
![image](https://github.com/typehero/typehero/assets/996134/87d432fe-9a7d-499b-9ad7-fd882782f273)

**Comment by bautistaaa** [comment]
> ![image](https://user-images.githubusercontent.com/996134/266746616-87d432fe-9a7d-499b-9ad7-fd882782f273.png)

https://media1.giphy.com/media/87xihBthJ1DkA/giphy.gif?cid=ecf05e4710s5wyc4r0teg5g0j2pqj3gwe0dsk6febuwfjwu7&ep=v1_gifs_search&rid=giphy.gif&ct=g

**Comment by PickleNik** [comment]
![image](https://github.com/typehero/typehero/assets/31113245/648e5077-0c15-4a60-b544-778223bc7e5f)

**Comment by Milind-Jamnekar** [comment]
also drop the typescript. Vanilla moment is here

**Comment by bautistaaa** [comment]
> also drop the typescript. Vanilla moment is here

this ain’t even a joke i’m full sending bun

**Comment by Milind-Jamnekar** [comment]
> > also drop the typescript. Vanilla moment is here
> 
> this ain’t even a joke i’m full sending bun

damn.. is this even possible tho

**Comment by mustardfrog** [comment]
https://doc.rust-lang.org/stable/book/

**Comment by laureanray** [comment]
Do we know if Bun would improve nextjs server or our workflow in general?

**Comment by Hacksore** [comment]
Notes from my testing
- patch packages is not working
- dev server is much faster
- still issues when install even via `bun i --yarn`
```
trash/bun ✗ $ bun i --yarn                                                                                                                                                                130 ↵
[0.45ms] ".env.production", ".env"
bun install v1.0.0 (822a00c4)
 + @repo/auth@workspace:packages/auth
 + @repo/db@workspace:packages/db
 + @repo/emails@workspace:packages/email
 + @repo/lint@workspace:tooling/config-eslint
 + @repo/monaco@workspace:packages/monaco
 + @repo/og-image@workspace:apps/og-image
 + @repo/tailwind@workspace:tooling/config-tailwind
 + @repo/tsconfig@workspace:tooling/config-typescript
 + @repo/ui@workspace:packages/ui
 + admin@workspace:apps/admin
 + scripts@workspace:tooling/scripts
 + web@workspace:apps/web

 12 packages installed [114.00ms]
Failed to install 8 packages
error: FileNotFound installing typehero
error: FileNotFound installing typehero
error: FileNotFound installing typehero
error: FileNotFound installing typehero
error: FileNotFound installing typehero
error: FileNotFound installing typehero
error: FileNotFound installing @repo/og-image
error: FileNotFound installing typehero
```

**Comment by Hacksore** [comment]
Can we close this now @bautistaaa?
