### ISSUE TITLE
[Feature]: Solution Comments should be linkable

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#648]
### Description

Currently the challenge comments are linkable. The same implementation should be applied to solution comments

**Comment by Milind-Jamnekar** [comment]
can you explain further ? what do you mean by linkable ?

**Comment by zawarudo** [comment]
Confirmed Solution Comments cannot be shared

I can handle this.

**Comment by bautistaaa** [comment]
> can you explain further ? what do you mean by linkable ?

on the regular challenge you can share deep links to comments. forgot to add it to the solution comments as well

**Comment by bautistaaa** [comment]
> Confirmed Solution Comments cannot be shared
> 
> I can handle this.

this exists already for challenge comments. you can probably leverage exactly what i did there
