### ISSUE TITLE
disable Comment input box while logged out

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#649]
the current flow:
 - you're an unsuspecting user tryna write up a nice little essay into the comment section
   - you hit send, but it asks u to login, you click on login, the page reloads, your essay is gone, you cry

new flow:
 - comment box is disabled (or not rendered entirely) and a message about needing to login to comment is shown in the comment drawer instead

**Comment by Milind-Jamnekar** [comment]
@bautistaaa assign me!

**Comment by vivekKumarSinghH** [comment]
@PickleNik Can I work on this issue!
