### ISSUE TITLE
[Feature]: Add e2e tests

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#652]
### Description

Not needed atm but soon.

Tired of things breaking

Options:
- cypress
- playwright
- other

**Comment by billc-dev** [comment]
I would like to work on this. We started to port from Cypress to playwright and really liked it. It's a newer tool with less baggage compared to cypress. 

Parallel testing is built in and you don't need to pay for it unlike cypress. We didn't have to install any plugins either as everything just worked.

Features (all built-in):
- Parallelization
- Easy setup for browsers (chrome, firefox, webkit)
- HTML reporter with trace viewer
  - Trace viewer records console output and network requests (similar to chrome devtools)
- Code generation

**Comment by oussamaBGZ** [comment]
> playwright

i think cypress is just fine for this project its very easy to setup with great doc and bigger community no need for a new tool i don't see the advantage, this is my opinion.

**Comment by basokant** [comment]
+1 for Playwright, it's based

**Comment by KaKashi1210** [comment]
echoing @oussamaBGZ, cypress setup is ez and one of the best docs out there

**Comment by jhechtf** [comment]
It's another +1 from me for Playwright. Have used it in some other projects and liked the flow of it.
