### ISSUE TITLE
[Bug]: Comment bar when collapsed partially covers the content

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#653]
### What happened?

Heres a video of the issue

![CleanShot 2023-09-11 at 13 01 49](https://github.com/typehero/typehero/assets/3660667/73928ca4-7ccf-48bb-a7de-a4d1ec09b455)

### What browsers are you seeing the problem on?

All

**Comment by oussamaBGZ** [comment]
i can work on this if no one started with it

**Comment by rockingrohit9639** [comment]
@bautistaaa is this issue fixed ?
