### ISSUE TITLE
[Bug]: Submit button disabled when not logged in

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#654]
### What happened?

It should show a tooltip to indicate that they need to be logged in.

Try to make this work with `Button` vs the native `button`

### What browsers are you seeing the problem on?

All

**Comment by maxdemaio** [comment]
I can try and pick this up! is there a specific area this would be in?

Or do we want this functionality with all usages of `Button`?

**Comment by maxdemaio** [comment]
Answered in VC: challenge view, can't submit code when you're not logged in.

**Comment by bautistaaa** [comment]
> Answered in VC: challenge view, can't submit code when you're not logged in.

if you could figure it out with `Button` vs button we can fix how we do it with the bookmark and upvote buttons

**Comment by maxdemaio** [comment]
Note: the message displayed will be "Log in to Submit"
