### ISSUE TITLE
[Bug]: Resetting code does not reset the tests status

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#662]
### What happened?

1. Solve a challenge.
2. Reset code.
3. Notice the tests are still passing

### What browsers are you seeing the problem on?

All

**Comment by cosmiclasagnadev** [comment]
I can take a look at this @bautistaaa 🫡

**Comment by bautistaaa** [comment]
issue still persists

**Comment by bautistaaa** [comment]
fixed with: https://github.com/typehero/typehero/commit/71624b8405fedca2a7c03a8cb8254776d43b2b65
