### ISSUE TITLE
[Bug]: Incorrect loading skeleton for solution details

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#664]
### What happened?

`challenge/2/submissions/2` is using the loading skeleton from its parent. need to create a loading skeleton inside `/solutions/[solutionId]`

**Comment by vivekKumarSinghH** [comment]
@bautistaaa  I can work on this!

**Comment by vivekKumarSinghH** [comment]
@bautistaaa  Does this loading skeleton look fine ? 
https://github.com/typehero/typehero/assets/72158561/2bb30359-8dd7-47e8-8e97-1b34951a9acb
