### ISSUE TITLE
[Bug]: Link input does not listen to all keystrokes, loses it's focus while typing after every character

### ISSUE THREAD

**Issue by aakash19here** [typehero/typehero#669]
### What happened?

A bug happened!

https://github.com/typehero/typehero/assets/86520455/ce914c94-663b-4659-9e78-5422a6f7841d

### What browsers are you seeing the problem on?

Chrome

**Comment by bautistaaa** [comment]
ahh another case of `million-ignore` search the codebase for it


you'll have to put it on the parent

**Comment by aakash19here** [comment]
No , its not an issue with million ,its with the react-hook-form , its re-rendering the component after every keystroke and thus the focus is not persistent , I have solved it and will raise a PR shortly

**Comment by aakash19here** [comment]
@bautistaaa review required
