### ISSUE TITLE
[Feature]: Add rows for each difficulty to explore page

### ISSUE THREAD

**Issue by WillGarman** [typehero/typehero#675]
### Description

Add the `BEGINNER` and `EXTREME` challenges to `/explore`

### Explanation

the `/explore` page portrays that the only difficulties of challenges that exist are:
- EASY
- MEDIUM
- HARD

you can see a sliver of `"EXTREME"` in the "Most Popular" or "Newest" rows but those rows are bound to change as new challenges come along. I think this raises a question of how will the users know there are actually: 
- BEGINNER (add to page)
- EASY
- MEDIUM
- HARD
- EXTREME (add to page)

I think the addition of the 2 rows to `/explore` is worth it for users to be able to see all difficulties

**Comment by SooditK** [comment]
my bad 😞
