### ISSUE TITLE
[Bug]: Incorrect links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by heyanurag** [typehero/typehero#678]
### What happened?

Links are broken in the CONTRIBUTING.md file.

- LOCAL.md and CODE_OF_CONDUCT.md and Issues links return a 404.
- See commits link doesn't show the repository commits

### What browsers are you seeing the problem on?

All

**Comment by jselmani** [comment]
Can I take this?

**Comment by bautistaaa** [comment]
fixed with https://github.com/typehero/typehero/pull/679

**Comment by bautistaaa** [comment]
> Can I take this?

lol he fixed it after he opened it

**Comment by jselmani** [comment]
> > Can I take this?
> 
> 
> 
> lol he fixed it after he opened it

Lol man I'm on my phone looking for tickets to pick up so I can contribute here. Code snipers in this project 🔫 👀
