### ISSUE TITLE
[Bug]: UI/Layout - Explore Page Looks off on Large Screens

### ISSUE THREAD

**Issue by laureanray** [typehero/typehero#686]
### What happened?

Explore Page looks weird on large screens (I feel like we could align this to the center?)
See screenshot
![image](https://github.com/typehero/typehero/assets/22195710/7af3dfc2-6278-4217-beb4-67322b95ea34)

### What browsers are you seeing the problem on?

All

### Relevant log output

```zsh
N/A
```

**Comment by oussamaBGZ** [comment]
I can work on this @bautistaaa
