### ISSUE TITLE
[Bug]: Expanding comment section in mobile displays parts of it underneath tabs

### ISSUE THREAD

**Issue by odicho** [typehero/typehero#699]
### What happened?

Collapsed comment section:
![image](https://github.com/typehero/typehero/assets/53154523/560a364a-e269-4745-92df-bd17daa2cd9c)

Expanded (the comment section expands to underneath the tabs):
![image](https://github.com/typehero/typehero/assets/53154523/172e8fbc-1f4f-493c-856c-8343c491309a)

Reproduction:
1. Use any mobile resolution
2. Go to any challenge
3. Click on "Comments" to expand

Fix:
This entire container's hight should be limited by its parent's container, which is already defined to be starting from underneath the tabs until the bottom of this section. An easy solution is to set `max-h-full` on the highest level `div` in the Comments component.

Expanded (post fix):
![image](https://github.com/typehero/typehero/assets/53154523/894a7c3f-b8a6-4179-91e0-b08d689a1ca1)

**Comment by Rand0mLetters** [comment]
I believe this is a problem on all displays, not just mobile, but the fix should fix it on all displays anyways.

**Comment by odicho** [comment]
It works just fine on desktop resolution for me:
![image](https://github.com/typehero/typehero/assets/53154523/b5e2e761-826c-4a8a-a4e4-b39a8dea30f4)

Either way, it will be a safeguard!
