### ISSUE TITLE
[Feature]: Lazy load comments

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#708]
### Description

comments should not be fetched on page load and should only be fetched when they are expanded.

### Explanation

currently if you load a challenge youll see a request per comment that has replies. we should only fetch if user intention is to see the replies.

**Comment by rockingrohit9639** [comment]
@bautistaaa can I work on this issue ?

**Comment by bautistaaa** [comment]
this was solved by side effect of https://github.com/typehero/typehero/pull/718

sorry about that!
