### ISSUE TITLE
[Feature]: load all replies when panel is expanded with load more behavior

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#711]
### Description

related: https://github.com/typehero/typehero/issues/708

when replies are expanded load all the replies in memory but paginate on the client.

see this for example: https://leetcode.com/problems/two-sum/description/comments/1565865

**Comment by oreoluwa-bs** [comment]
can I work on this issue?

**Comment by bautistaaa** [comment]
> can I work on this issue?

sure

**Comment by bautistaaa** [comment]
be mindful of the individual working on the other related task

**Comment by oreoluwa-bs** [comment]
Alright thank you
