### ISSUE TITLE
[Bug]: Challenge card code lines colors

### ISSUE THREAD

**Issue by DevWig** [typehero/typehero#722]
### What happened?

On the landing page in the challenge cards preview, the color of the lines of code do not change when dark/light mode is toggled and they look very out of place in light mode

**Comment by oussamaBGZ** [comment]
I could work on this @bautistaaa

**Comment by QuiiBz** [comment]
I think it's this part:

| Dark | Light |
|--------|--------|
| ![image](https://github.com/typehero/typehero/assets/43268759/305baa1d-1724-4936-afbb-912d2d59f552) | ![image](https://github.com/typehero/typehero/assets/43268759/04674366-ab56-4555-924f-43a1c5f11225) |

We use the same colors in the tracks page btw.

**Comment by oussamaBGZ** [comment]
It looks good i don't see the problem

**Comment by bautistaaa** [comment]
its this

<img width="1275" alt="CleanShot 2023-09-26 at 06 44 41@2x" src="https://github.com/typehero/typehero/assets/3660667/3730c485-274d-4158-a850-803b50185eeb">


type hero text needs to be tweaked too

**Comment by DevWig** [comment]
Sorry, I thought I added the screenshot. I'm still getting used to the GitHub UI. @bautistaaa is right though.
I'd love to work on this if that's okay.

**Comment by DevWig** [comment]
PR approved and merged
