### ISSUE TITLE
[Feature]: The Add url field does not have any remove button

### ISSUE THREAD

**Issue by aakash19here** [typehero/typehero#724]
### Description

If the user accidentally clicks on add url he does not have any options to remove the field 
<img width="916" alt="Screenshot 2023-09-27 at 11 23 05 AM" src="https://github.com/typehero/typehero/assets/86520455/18268f95-cc07-41d0-a435-dad0618ab52a">

**Comment by bautistaaa** [comment]
closing. make new ticket regarding the adding some of the new ui back
