### ISSUE TITLE
[Bug]: Deep link replies that are in nested "pages" on the reply thread

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#738]
### What happened?

Currently if you try to deep link a reply that is not on the initial page it will not find it

**Comment by ayrock-dev** [comment]
Taking this up! I see #718 went in, I'll build from there

**Comment by bautistaaa** [comment]
quick thing i tried: calculate initial page(same formula as how we do it for top level comments) and feeding the initial page to `infiniteQuery`

it "worked" in the sense that it loading the right page but you can really go forwards or backwards. i think you might need traditional paging to make it work like the top level comments.

for example:

deep link a reply on "Page" 4 of 10. then what? is there show previous/next? can probably look at leetcode on how they handle this

**Comment by ayrock-dev** [comment]
Leetcode behavior:

 1. comments load with replies collapsed
 1. clicking [Show 24 Replies] expands replies, the first 5 are visible with a [Show more replies] link beneath them
 1. clicking [Show more replies] appends 5 more replies to the list. after clicking once, there are 10 total replies in-view
 1. clicking [Share] on, say, the 23th item copies link to clipboard
 1. opening the link in a new tab deep links and scrolls to the intended reply, with replies expanded and 23 total replies in-view
 
 All but that last one (5.) is implemented. On it.

Example deep link: https://leetcode.com/problems/two-sum/description/comments/1699015
