### ISSUE TITLE
[Bug]: Type Challenge card assets are too small on mobile

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#750]
### What happened?

they should fill up more space 

<img width="372" alt="CleanShot 2023-10-01 at 22 21 51@2x" src="https://github.com/typehero/typehero/assets/3660667/52ee2817-0c60-41ff-8fcb-593b986dea93">

**Comment by borisnezlobin** [comment]
How so? Just move them up? I can play around with this

**Comment by bautistaaa** [comment]
> How so? Just move them up? I can play around with this

whatever looks good

**Comment by borisnezlobin** [comment]
#758 is ready to merge (after review)
