### ISSUE TITLE
[Feature]: Consolidate Pill-Shaped Button Variant

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#755]
### Description

Several feature areas of TypeHero leverage a pill-shaped button. We can align this button style into a single re-usable variant.

Today, the pill-shaped button style is used in the following areas (and possibly others).
|Feature|Current UX|
|---|---|
|Challenge Description|<img width="515" alt="image" src="https://github.com/typehero/typehero/assets/7817695/48e5503b-9757-4d04-9399-5a8b4452a066">|
|Challenge Comment, Solution Comment|<img width="509" alt="image" src="https://github.com/typehero/typehero/assets/7817695/a5c5d14e-92db-463c-b672-d41d5001c938">|
|Solution List|<img width="512" alt="image" src="https://github.com/typehero/typehero/assets/7817695/eccb26d4-777b-4fd4-b922-7461280f697c">|
|Solution Description|<img width="508" alt="image" src="https://github.com/typehero/typehero/assets/7817695/f5cac379-b5e2-40f2-9525-22b065f814d2">|

### Action Items

 - [ ] Create a `badge` button variant that uses the same styles (`rounded-full`, etc) we are already using on a case-by-case basis today.
 - [ ] Use this button variant across use-cases shown above.
   - [ ] Challenge Description
   - [ ] Challenge Comment
   - [ ] Solution Comment
   - [ ] Solution List Item
   - [ ] Solution Description
   
 ### Considerations

 - [ ] The new variant may need to be compatible/composable with other color variants (destructive, etc)

**Comment by PickleNik** [comment]
@ayrock-dev is this done? Can be closed?
