### ISSUE TITLE
[Bug]: Badge Hover Colors

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#756]
### What happened?

Today, some badges have an incorrect hover color. All badges are appearing blue on hover, even for a badge that is originally red, brown, green, yellow, etc.

For example, on a challenge description or home feature card (among other usages).

|Feature|Current UX|
|---|---|
|Challenge Description|<img width="350" src="https://github.com/typehero/typehero/assets/7817695/b0739600-e305-4966-9dcc-e29df49f7673" >|
|Home Feature Card|<img width="350" src="https://github.com/typehero/typehero/assets/7817695/6d389fbc-46fd-4a52-9db4-ed3eb1248f32">|

### Action Item

Solution Options
- [x] Option A: Badges are non-interactive by default, and perhaps should not have a hover color (which implies interactivity).
- [ ] ~Option B: Badges should have a hover color matching their color variant. For example, a shade of green hover for green badge, and so on.~
- Verify badge is a `span` or similar element, not a button for a non-interactive badge.
- Separate badge variants/styles if appropriate and simple with this change.

### What browsers are you seeing the problem on?

All

**Comment by ayrock-dev** [comment]
@bautistaaa @PickleNik is A or B preferred?

**Comment by ayrock-dev** [comment]
> @bautistaaa @PickleNik is A or B preferred?

Team prefers "Option A" on discord: :axe: the hover state.

**Comment by adapodaca92** [comment]
Can I work on this?

**Comment by adapodaca92** [comment]
Looks like this commit https://github.com/adapodaca92/typehero/commit/86348256fe8a6133d43e3c5f380f8cfab9dfc374#diff-9a2d07326a71e3411ff65f12b60744f322138c563d3b12a117df850cee7a2e23 for #760 fixes this.

**Comment by adapodaca92** [comment]
Looks like this commit https://github.com/typehero/typehero/pull/760/commits/d7834580fced33b578c22e8f4b4902bd164f316c for #760 fixes this.

**Comment by bautistaaa** [comment]
ah indeed sorry about that
