### ISSUE TITLE
[Bug]: Editor shortcuts

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#761]
### What happened?

Some of the editor shortcuts are invalid. Additionally, they dont account for the users Operating System and always displays `ctrl` 

This ticket involves a couple requirements

- [ ] detect operating systems and display `ctrl` or `cmd` accordingly. 
- [ ] remove shortcuts that dont apply (ex: `Run Code` can be deleted)
- [ ] adjust shortcuts that arent accurate (ex: indent one level is `TAB or ⌘ + ]`
- [ ] any other improvements i may have missed

### Current List
<img width="590" alt="CleanShot 2023-10-02 at 22 24 02@2x" src="https://github.com/typehero/typehero/assets/3660667/5f042b2f-536b-4a3a-a72c-37fbef11f78b">

can use leetcode for reference
https://leetcode.com/problems/two-sum/

**Comment by vivekKumarSinghH** [comment]
@bautistaaa Please assign this issue to me
