### ISSUE TITLE
[Feature] RFC: improve repo docs

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#763]
### Overview

Add a `docs` folder to jot down decisions and procedures.

#### Terminology

 - **Decision**: A choice was made, why did we add that lib or choose a monorepo?
 - **Procedure**: How did we do the thing? How can someone do it again next time?
 
Writing these down these answers
 - lowers the bar for onboarding new contributors,
 - is a good reminder for all contributors down the road (us humans are forgetful), and
 - is an awesome resource for the community to learn from.

### Proposal

My proposed example folder structure, inspired by Kent C Dodds' [Epic Stack docs](https://github.com/epicweb-dev/epic-stack/tree/main/docs)
```
.
├── apps
├── packages
├── docs/
│   ├── README.md
│   ├── decisions/
│   │   ├── 000-template.md
│   │   ├── 001-monorepo.md
│   │   ├── 002-typescript.md
│   │   └── ...
│   └── procedures/
│       ├── 000-template.md
│       ├── 001-update-contributors.md
│       ├── 002-run-e2e-tests.md
│       └── ...
└── ...
```

#### Proposed Format

See [Kent C Dodds' decision doc](https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/000-template.md) template, it's pretty concise and to-the-point. 

#### Proposed Level of Effort

The intent for any one decision doc or procedure is to be minimal effort. Click through [a few of Kent C Dodds' decision docs](https://github.com/epicweb-dev/epic-stack/tree/main/docs/decisions) and see that these are SUPER insightful little blurbs and some are only a few senetences.

### Next Steps

I can implement structure and first doc (likely steps to run e2e tests) if we vibe with this.

I will likely reach out to:
 - @bautistaaa to author a monorepo and typescript decision doc (maybe something something vercel too)
 - @billc-dev to help me improve the e2e doc
 - @QuiiBz to write down how the update contributor ci works

**Comment by bautistaaa** [comment]
I do think there is value around documenting how certain things work. I am not convinced the decision stuff should be documented. Mainly because its usually just me thinking about such things tbh.
