### ISSUE TITLE
[Feature]: idempotent e2e test suite setup

### ISSUE THREAD

**Issue by ayrock-dev** [typehero/typehero#764]
## Goal
We can make it easier to run the Playwright E2E tests locally.

### Explanation
We can improve the `test:e2e` workflow by making e2e setup idempotent, which is friendlier for local dev where the dev db may not always be in a clean-slate state.

(By contrast, the db is always in a clean-slate state in `ci` runs. See `workflows/quality.yml` for the steps the E2E action goes through.)

### Action Items
 - [ ] Always publish e2e report even for a failed run (add `if: always()` to publish steps in `workflows/quality.yml`)
 - [ ] Use `createOrConnect` over basic `create` for the Playwright `setup()` scripts

An example of the latter looks like the following. Without this step the `create` operation fails on a unique constraint if the record already exists.
```diff
  await prisma.user.upsert({
    where: {
      email: USER.email,
    },
    create: {
      id: USER.id,
      . . .
      roles: {
-       create: {
-         role: 'USER',
-       },
+       connectOrCreate:
+         where: {
+           role: 'USER',
+         },
+         create: {
+           role: 'USER',
+         },
+       },
      },
```

cc @billc-dev for thoughts.

**Comment by billc-dev** [comment]
@bautistaaa can you assign this to me
