### ISSUE TITLE
[Bug]: Dark mode profile bio wrong theme colors

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#772]
### What happened?

When you first pull up to the profile in dark mode you see this but if you toggle to light mode then back to dark it goes away.

Notice the bio field has:
- wrong box shadow color
- text color is not visible

![image](https://github.com/typehero/typehero/assets/996134/21b2731d-066c-4905-b449-556910f82da3)

**Comment by MrVSiK** [comment]
Hi! I'd like to give this a shot

**Comment by Hacksore** [comment]
I'll assign it to @MrVSiK since he was first, looking forward to the PR.
