### ISSUE TITLE
[Feature]: add `gcc` to vim mode to comment

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#773]
### Description

https://github.com/typehero/typehero/issues/399#issuecomment-1747420726

but tl;dr `gcc` to block comment in vim mode.

**Comment by ggrandi** [comment]
@Hacksore so far I did a quick look through and the easiest thing to do is to add the following line to the vim config:
```
nmap gcc :M<Space>editor.action.commentLine
```
however this only comments a single line. for visual mode I keep running into bugs so it'll take a little bit to fix

**Comment by Hacksore** [comment]
for now will do what you said but some how it works in VSCode Vim extensions so will have to peep that source.

https://github.com/VSCodeVim/Vim/issues/2933
