### ISSUE TITLE
[Feature]: show links on settings page

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#776]
### Description

Settings page should have the links shown under the bio, like dis.
![image](https://github.com/typehero/typehero/assets/996134/5f2ad708-3b5b-4d16-a1c0-22181a9131ab)

It already does it on the profile page:
![image](https://github.com/typehero/typehero/assets/996134/e7a21ae1-171e-4cb2-b7ed-aefb18854844)

**Comment by sital002** [comment]
I would like to work on this issue

**Comment by Hacksore** [comment]
@sital002 :shipit:
