### ISSUE TITLE
[Bug]: Only build metadata for user if path starts with `/@`

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#778]
### What happened?

right now `/challenge` seems to be using the `buildMetaForUser` but it should only do that if the route starts with an `/@` otherwise it should fallback to using `buildMetaForDefault`.

So:

- /challenge ([buildMetaForDefault](https://github.com/typehero/typehero/blob/main/apps/web/src/app/metadata.ts#L108)) 
- /@challange ([buildMetaForUser](https://github.com/typehero/typehero/blob/main/apps/web/src/app/metadata.ts#L64))

bug screenshot image when viewing `/challenge`:
![image](https://github.com/typehero/typehero/assets/996134/d586aaac-fb72-4cfa-9d6f-f16b2b293456)

**Comment by sital002** [comment]
I would like to work on this issue.

**Comment by Hacksore** [comment]
@sital002 :shipit:
