### ISSUE TITLE
[Feature]: Use new typehero logo in the og images

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#781]
### Description

@PickleNik we need to update the figma

https://www.figma.com/file/bMKdaJ6OxBVvYuX5emrXXN/Typehero?type=design&node-id=284-103&mode=design&t=E9HMduUTCvpr2Okg-0

### Explanation

they are still using the old ones
https://og.typehero.dev/

**Comment by Parthvsquare** [comment]
@Hacksore can i take this?

**Comment by Hacksore** [comment]
@Parthvsquare :shipit:
