### ISSUE TITLE
[Bug]: support list in the markdown editor

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#785]
### What happened?

The markdown editor should support both kinds of ordered lists.

<img width="873" alt="image" src="https://github.com/typehero/typehero/assets/996134/5f849b57-8ea0-47d7-8d78-f93317352d47">

**Comment by vivekKumarSinghH** [comment]
@Hacksore @bautistaaa please assign it to me

**Comment by vivekKumarSinghH** [comment]
@bautistaaa @Hacksore The number list is not appearing on preview, I believe it is an issue with the react-md-editor library
related issue-https://github.com/JedWatson/react-md-editor/issues/19

![image](https://github.com/typehero/typehero/assets/72158561/d625184b-30ab-4674-a733-cded9f44e32c)
![image](https://github.com/typehero/typehero/assets/72158561/20e5d296-23a5-4639-9448-4bbcb7f3d9d9)

**Comment by bautistaaa** [comment]
nooooooooo

**Comment by vivekKumarSinghH** [comment]
> nooooooooo
@bautistaaa help needed!
Still facing the same issue when using the same library in a new next JS project

![image](https://github.com/typehero/typehero/assets/72158561/c37b8224-a86c-492a-a7db-340a91cf9ed2)

**Comment by Hacksore** [comment]
looks like it's tailwind setting a reset on `ol` items  removing the `list-style`.


https://github.com/typehero/typehero/assets/996134/27507128-4973-4e6a-b14a-62b9f1585f4c
