### ISSUE TITLE
[Bug] if you refresh the /wizard page you lose all your progress

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#786]
### What happened?

use onbeforeunload on this page to prevent data loss on the wizard page.

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by MrVSiK** [comment]
Hello! It seems this can be resolved by adding the event listener in useEffect. I can take this up. Could you please assign it to me?

**Comment by Hacksore** [comment]
@MrVSiK :shipit:
