### ISSUE TITLE
[Bug]: VIM input breaks when showing type info twice

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#802]
### What happened?

repro:

1. go to any challenge
2. enter vim mode
3. move your editor cursor on a symbol/var
4. `SHIFT` + `k` twice
5. borked

---

https://github.com/typehero/typehero/assets/996134/b1cce554-153c-447e-9b70-824a1ab8eeb7

**Comment by Hacksore** [comment]
@ggrandi might have some ideas what's going on here.

**Comment by heathhenley** [comment]
I reproduced this on brave, you can also reproduce it if you mouse over to let the type info tooltip open and then press shift + K to  trigger the command again.

It seems like running `showHover` when the tooltip is already open toggles the tooltip back to hidden, but it's not focusing the main editor window so you have to click to refocus before you can continue vim'ing. 

I'm a bit lost about where the action is actually defined, I ag'ed for it in this repo and monaco so I think I'm missing something. I would be happy to attempt to fix it someone could point me to it?

I think this shows that the div with the editor is not getting properly refocused if you run `showHover` when the tool tip is already open:

https://github.com/typehero/typehero/assets/5819478/70b8feb9-a912-4203-aaa0-51c94a6be16d

**Comment by heathhenley** [comment]
Thanks @Hacksore! Yeah I'm getting there too, but I'm a little lost on going further down into the stack. I thought I would see that action "editor.action.showHover" in typehero, in the monaco-vim repo or the monaco-editor repo but I haven't been able to wrap my head around it. Maybe I can step in with a debugger or something... tbd

**Comment by Hacksore** [comment]
@heathhenley I'd say raise a PR and tag me if it works we ship it.

🙏

**Comment by Hacksore** [comment]
not super important
