### ISSUE TITLE
[Feature]: Authors of a solution should be able to delete them

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#804]
### Description

Just like an author can delete their own comment, they should be able to delete their solution.

Add a delete button next to the others
<img width="557" alt="CleanShot 2023-10-08 at 01 00 01@2x" src="https://github.com/typehero/typehero/assets/3660667/56bf3853-450f-4630-b928-af85aef0d433">

**Comment by zaCKoZAck0** [comment]
If Possible, I want to work on this.
