### ISSUE TITLE
[Bug]: Admin tabs do not load data until you refresh

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#810]
### What happened?

Often times when you load admin portal the tabs are either stuck in a loading state or nothing appears until you refresh.

**Comment by adapodaca92** [comment]
Can I tackle this?

**Comment by adapodaca92** [comment]
Unassigned myself to give someone else the opportunity to work this more timely as still runing into issues with my local set up...yay!

**Comment by shlok-2003** [comment]
hey @bautistaaa, can you assign this issue to me

**Comment by shlok-2003** [comment]
hey @bautistaaa, how can I recreate the issue in my laptop.

**Comment by bautistaaa** [comment]
> hey @bautistaaa, how can I recreate the issue in my laptop.

give yourself admin (in the instructions)

navigate to localhost:3001 to see admin dashboard

**Comment by ja153903** [comment]
@bautistaaa Is this still reproducible?
