### ISSUE TITLE
[Feature]: OG Image for user profiles

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#815]
### Description

use the challenge card as inspiration.

can viewed at https://og.typehero.dev/

see if you can grab the user avatar and clamp the user bio maybe? i doubt many will actually have the bio filled out so get creative

**Comment by falcon-head** [comment]
@bautistaaa please assign this to me!

**Comment by Hacksore** [comment]
@falcon-head :shipit:

**Comment by falcon-head** [comment]
How are feeling about this?


![image](https://github.com/typehero/typehero/assets/32938743/f09541d6-0345-4304-b605-596ec238e70f)

**Comment by Hacksore** [comment]
@falcon-head :shipit: it we can improve later!
