### ISSUE TITLE
[Feature]: Add primary color on drag/hover of editor split

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#826]
### Description

similar to VSCode can we make the little grabber turn the primary blue color when hover/dragging?

https://github.com/typehero/typehero/assets/996134/e7a7cf37-0c31-4648-a48a-49c90e4723d9

**Comment by shlok-2003** [comment]
Hey @Hacksore, I would love to work on this issue

**Comment by shlok-2003** [comment]
I have made the necessary changes in the resizer
