### ISSUE TITLE
[Bug]: contributors query not pulling all contributors

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#830]
### What happened?

contributors.ts is missing a lot of contributors.

check the contributors script to see why

**Comment by zaCKoZAck0** [comment]
I think it's related to this [https://github.com/octokit/octokit.js#pagination](https://github.com/octokit/octokit.js#pagination) , that's why it's returning only first 30 results.

**Comment by bautistaaa** [comment]
> I think it's related to this https://github.com/octokit/octokit.js#pagination , that's why it's returning only first 30 results.

yeah that was  my initial guess wanna take this?

**Comment by zaCKoZAck0** [comment]
Creating a draft PR, check it.
