### ISSUE TITLE
[Bug]: markdown editor bugged in dark mode

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#831]
### What happened?

initially displaying the markdown editor shows incorrectly. its not always consistently broken though and toggling the light and dark mode fixes it. my initial hunch is on mount its not detecting the theme properly

![CleanShot 2023-10-10 at 14 08 27](https://github.com/typehero/typehero/assets/3660667/f399e493-a056-4fd4-8ce6-7b4a191b7788)

**Comment by zaCKoZAck0** [comment]
How to reproduce this?

**Comment by Hacksore** [comment]
Is this somehow related to #783?

**Comment by Hacksore** [comment]
@MrVSiK askin for your thoughts here, thanks!

**Comment by bautistaaa** [comment]
> How to reproduce this?

you have to have a successful solution to submit. you can override it in the actual code to enable

**Comment by MrVSiK** [comment]
@Hacksore thanks for the ping. At first glance it seems to have the same problem as #772. 
![Theme code](https://github.com/typehero/typehero/assets/79159341/c5ba9956-c017-49b4-988b-303280183c6b)

`next-theme` by default allows `system` value to be set in local storage. As seen from above, it picks the wrong theme in the conditional logic since `system` isn't handled.

A simple switch case with a default block should solve the problem.

**Comment by bautistaaa** [comment]
> @Hacksore thanks for the ping. At first glance it seems to have the same problem as #772. ![Theme code](https://user-images.githubusercontent.com/79159341/274129879-c5ba9956-c017-49b4-988b-303280183c6b.jpg)
> 
> `next-theme` by default allows `system` value to be set in local storage. As seen from above, it picks the wrong theme in the conditional logic since `system` isn't handled.
> 
> A simple switch case with a default block should solve the problem.

is there a way to couple this logic so it can always do the right thing

**Comment by zaCKoZAck0** [comment]
> > @Hacksore thanks for the ping. At first glance it seems to have the same problem as #772. ![Theme code](https://user-images.githubusercontent.com/79159341/274129879-c5ba9956-c017-49b4-988b-303280183c6b.jpg)
> > `next-theme` by default allows `system` value to be set in local storage. As seen from above, it picks the wrong theme in the conditional logic since `system` isn't handled.
> > A simple switch case with a default block should solve the problem.
> 
> is there a way to couple this logic so it can always do the right thing

I think adding these props to ThemeProvider will do trick, `defaultTheme="system" enableSystem`. Then you won't be needing this.

**Comment by zaCKoZAck0** [comment]
> > > @Hacksore thanks for the ping. At first glance it seems to have the same problem as #772. ![Theme code](https://user-images.githubusercontent.com/79159341/274129879-c5ba9956-c017-49b4-988b-303280183c6b.jpg)
> > > `next-theme` by default allows `system` value to be set in local storage. As seen from above, it picks the wrong theme in the conditional logic since `system` isn't handled.
> > > A simple switch case with a default block should solve the problem.
> > 
> > 
> > is there a way to couple this logic so it can always do the right thing
> 
> I think adding these props to ThemeProvider will do trick, `defaultTheme="system" enableSystem`. Then you won't be needing this.

[https://github.com/pacocoursey/next-themes#themeprovider](https://github.com/pacocoursey/next-themes#themeprovider)

**Comment by Hacksore** [comment]
seems it's default 🤨https://github.com/pacocoursey/next-themes?tab=readme-ov-file#use-system-preference-by-default

**Comment by zaCKoZAck0** [comment]
> seems it's default 🤨https://github.com/pacocoursey/next-themes?tab=readme-ov-file#use-system-preference-by-default

Mb

**Comment by MrVSiK** [comment]
> I think adding these props to ThemeProvider will do trick, defaultTheme=\"system\" enableSystem. Then you won't be needing this.

I believe that's the default configuration. Setting the `defaultTheme` to either `light` or `dark` would work.

However, I feel that there is a use case for `system`. If the user has enabled light or dark mode in their local machine then this variable will set the theme accordingly. Should this behaviour be removed? 

Do share your viewpoints

**Comment by zaCKoZAck0** [comment]
It won't always override with "system" theme until it's explicitly set to "system", if you select a theme. It will be set to that until changed.
There will be three options. Light | Dark | System
In "light" and "dark" mode it won't change until the user says so.
In "system" it won't change until you enable/disable dark mode on your system.

**Comment by DevWig** [comment]
@bautistaaa I can take this issue if no one has taken it yet

**Comment by bautistaaa** [comment]
> @bautistaaa I can take this issue if no one has taken it yet

let me check if @zaCKoZAck0 or @MrVSiK wanted to address first since they are active in the thread

**Comment by bautistaaa** [comment]
@DevWig no one said anything ill assign to you if thats okay
