### ISSUE TITLE
[Feature]: deleteComment should only allow authorized users to delete

### ISSUE THREAD

**Issue by Hacksore** [typehero/typehero#836]
### Description

Please add logic to only allow deletion of a comment if it's a
- comment author
- moderator
- admin

https://github.com/typehero/typehero/blob/2cc8bb8196ea387c63acb0cf495c97ce11e6da18/apps/web/src/app/%5Blocale%5D/challenge/_components/comments/comment.action.ts#L86

**Comment by bautistaaa** [comment]
admin or mods should be able to delete as well

**Comment by vivekKumarSinghH** [comment]
Please assign this to me @bautistaaa
