### ISSUE TITLE
[Feature]: Redesign the contributors layout

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#837]
### Description

We have reach a point where we have too many contributors for the community section. We need to make the rows wider so it doesnt grow so tall or some other design. 

<img width="1681" alt="CleanShot 2023-10-10 at 22 44 23@2x" src="https://github.com/typehero/typehero/assets/3660667/845580ed-c371-4e93-898e-5c2811559805">

**Comment by vivekKumarSinghH** [comment]
Please assign it to me @bautistaaa

**Comment by PickleNik** [comment]
I'd just 40/60 or 30/70 width of the text vs the grid

**Comment by PickleNik** [comment]
also maybe out of scope but it'd be cool if rows got indented towards the middle so the shape of the grid followed kinda like a semicircle hugging the text
<img width="1681" alt="274153662-845580ed-c371-4e93-898e-5c2811559805" src="https://github.com/typehero/typehero/assets/31113245/cd68ed86-b54b-46f6-9498-2a54ceb4b61c">

**Comment by PickleNik** [comment]
for the future if we run out of space completely the rows could maybe infinite-scroll in opposite directions with a linear-gradient image-mask on the sides, just throwing ideas out there

**Comment by PickleNik** [comment]
oh and on mobile it shouldn't have a padding and each grid item size could be decreased as well
<img width="393" alt="Screenshot 2023-10-11 at 10 43 35 AM" src="https://github.com/typehero/typehero/assets/31113245/5cebcff9-957e-4d9c-9458-8de1c39beb8e">

**Comment by bautistaaa** [comment]
assigning to both of you. more variations the better and we can pick

**Comment by Parthvsquare** [comment]
what about horizontal scrolling?

**Comment by PickleNik** [comment]
> what about horizontal scrolling?
<img width="936" alt="Screenshot 2023-10-11 at 5 10 42 PM" src="https://github.com/typehero/typehero/assets/31113245/a23014a5-26f5-422c-a170-16066f4a81c5">

**Comment by Hacksore** [comment]
the best way forward is making it show top N then having a dedicated `/contributions` route with all of us 🫂.

**Comment by PickleNik** [comment]
> the best way forward is making it show top N then having a "see all button" with a dedicated `/contributors` to show us all 🫂.

the ui:
![image](https://github.com/typehero/typehero/assets/31113245/c6abf0e2-3c81-4e4b-ae55-ea46639aabdd)

**Comment by bautistaaa** [comment]
> the best way forward is making it show top N then having a "see all button" with a dedicated `/contributors` to show us all 🫂.

@vivekKumarSinghH @PickleNik yeah lets keep the original component the same and add a view all contrib button and just create a new `/contributors` route

design up to yall

**Comment by bautistaaa** [comment]
that means we have to revert the changes to paginate the results for this one and use that instead for the new route

**Comment by PickleNik** [comment]
I mucked up the component a bit with my latest PR in attempt to make it a semi-circle, I think I can simplify it today

**Comment by PickleNik** [comment]
> that means we have to revert the changes to paginate the results for this one and use that instead for the new route

Wait we had pagination?

**Comment by PickleNik** [comment]
I think I have an idea, we make it compact and automatically infinite-scrolling for the landing page, but on hover it will overlay with "click to view all contributors" which will redirect to contributors page

**Comment by PickleNik** [comment]
> > the best way forward is making it show top N then having a "see all button" with a dedicated `/contributors` to show us all 🫂.
> 
> @vivekKumarSinghH @PickleNik yeah lets keep the original component the same and add a view all contrib button and just create a new `/contributors` route
> 
> design up to yall

Do we even need a new route for that? Me thinks GitHub contributors view works

**Comment by bautistaaa** [comment]
> > > the best way forward is making it show top N then having a "see all button" with a dedicated `/contributors` to show us all 🫂.
> > 
> > 
> > @vivekKumarSinghH @PickleNik yeah lets keep the original component the same and add a view all contrib button and just create a new `/contributors` route
> > design up to yall
> 
> Do we even need a new route for that? Me thinks GitHub contributors view works

fair enough. just thought it would be a nice thanks in some sense to those that have smaller contributions. fine either way! if we go the github route lets revert the cron job changes. lmk what you decide and ill revert

**Comment by bautistaaa** [comment]
> > that means we have to revert the changes to paginate the results for this one and use that instead for the new route
> 
> Wait we had pagination?

thats why the list got so big cause we enabled it

**Comment by PickleNik** [comment]
> lmk what you decide and ill revert
Idk what u mean by reverting cron jobs but we still need all the contributors on landing page, they will just be showin in a more compact way

**Comment by zaCKoZAck0** [comment]
Just putting my thoughts here, can we make it infinite-scrolling, it will be animated i.e auto scrolling and everyone's picture will be visible at some point eventually.
Like some websites do with their sponsors because you gotta show each one of them as well 😉 .

**Comment by zaCKoZAck0** [comment]
That way we can keep the previous layout (before paginated contributors) just make it auto scroll and add an infinite-scrolling effect to it.

**Comment by bautistaaa** [comment]
@PickleNik looks like its changed, we good here or nah (assuming we still need the scroll stuff)

**Comment by PickleNik** [comment]
> @PickleNik looks like its changed, we good here or nah (assuming we still need the scroll stuff)

what's changed? scroll stuff is the plan i just haven't had the time to work on it yet

**Comment by bautistaaa** [comment]
no rush, i meant that it accommodates the list better now. this design will hold for a bit
