### ISSUE TITLE
[docs]: herodevs-logo-not-legible-on-README-in-gh-lightmode

### ISSUE THREAD

**Issue by papadavis47** [typehero/typehero#853]
### What happened?

herodevs logo in README is not legible in GitHub light mode due to white text on white background.

![light-mode-before](https://github.com/typehero/typehero/assets/33148009/980bc02b-b489-46fd-a5c1-51f2f495bc9d)

Issue is addressed in pr #852

**Comment by eduardoRoth** [comment]
My bad, didn't see that you already had a PR for it 😅. Yet, my PR uses two images for light and dark mode; and it removes the BG of the logo. Also, it removes the background of the image.

**Comment by papadavis47** [comment]
> My bad, didn't see that you already had a PR for it 😅. Yet, my PR uses two images for light and dark mode; also, it removes the background of the image.

It's cool, man. Yours seems the better solution. Bravo 👍🏼
