### ISSUE TITLE
[Bug]: Landing page has `<head>` metadata from other page routes

### ISSUE THREAD

**Issue by ernestoresende** [typehero/typehero#859]
### What happened?

During build, metadata from the landing page is being generated using information from other routes, eventually jumping around between multiple children routes on different build results. This seems to be a bug on Next's end.

One piece of context I'll put here is that the "jumping around" nature of the page it chooses in order to generate the landing page metadata seems to also include the landing page itself, which led me to believe that the problem had been previously solved by some of the first commits. Keep that in mind when debugging locally. 

Also important, the bug is not reproductible in development mode. You'll need to test changes by running and serving a build in order to see the bug occurring.

References to issues that could be related found by @QuiiBz: 
- https://github.com/vercel/next.js/issues/49988

### What browsers are you seeing the problem on?

All

**Comment by ernestoresende** [comment]
Exploring it further it seems it is not defaulting to just the `/explore` route's title, but rather jumping around between titles from multiple other routes when generating metadata at build time, as I've now managed to get `ToS | TypeHero` on the landing page title after the last triggered build.

I see that `metadata.ts` on the `web` workspace has the correct metadata definitions for the page segment: 

https://github.com/typehero/typehero/blob/86e00bfff9306b8f3cd8fb2f60397e7bb3ed228b/apps/web/src/app/metadata.ts#L10-L13

Is it possible that some dependency bump broke Next's metadata API?

**Comment by ernestoresende** [comment]
Also noticed that it's not affecting only the page title, but the entire page's `<head>` metadata. The following screenshot comes from the landing page:

![Screenshot 2023-10-13 at 14 15 38](https://github.com/typehero/typehero/assets/55156145/34916bd3-ea96-4b7a-bdce-5511930b99bf)

**Comment by maxdemaio** [comment]
Adding a link to the documentation for research and reference here: https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template

**Comment by ernestoresende** [comment]
@Hacksore Be aware that #867 does not solve the underlying problem here. 

The title is correct due to the override, but the metadata generator is still looking for metadata on other routes. For example, this is how the `<head>` looks on the current prod build:

![image](https://github.com/typehero/typehero/assets/55156145/c1a26492-5deb-41a7-a02d-8d3299929140)

It's reading metadata from the Terms of Service page.

**Comment by Hacksore** [comment]
> [!IMPORTANT]
> wtf next js

**Comment by ernestoresende** [comment]
Updated the issue description with the same content from my previous PR attempt at fixing this to more accurately describe the problem.
