### ISSUE TITLE
[Feature]: Finalize profile

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#875]
### Description

goals
 - [x] profile
   - [x] keep bookmarks, verify it works
   - [x] keep solutions, verify it works
   - [x] axe comments
   - [x] probably want to lower the chars you can use in bio to 1k or something reasonable (GitHub uses 160 characters)
 - [x] settings
   - [x] axe profile image/username since that's on ur public profile
   - [x] axe username field
   - [x] axe email field
   - [x] add button to navigate back to profile
 - [x] maintain `/settings` route to navigate there directly
 - [ ] fit-and-finish polish any wonky ux for early access

**Comment by ayrock-dev** [comment]
the public profile piece of this is done in #882

**Comment by ayrock-dev** [comment]
the settings page piece of this is done in #892
