### ISSUE TITLE
[Bug]: code in header tags in markdown renders wrong

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#886]
### What happened?

`Pick` should be the same font size in the markdown viewer

<img width="315" alt="CleanShot 2023-10-17 at 11 18 24@2x" src="https://github.com/typehero/typehero/assets/3660667/fa672a7f-364d-4d67-ae6b-5cb4794920b0">

- run `pnpm db:prod:seed`
- youll see the challenges on the explore page and clicking on any of them will present the problem (`/explore`)

**Comment by Anish-Sarawgi** [comment]
@bautistaaa Can you please assign it to me?

**Comment by Anish-Sarawgi** [comment]
@bautistaaa can you add the link of the file where this issue exist. I can't find this problem anywhere.

**Comment by bautistaaa** [comment]
run `pnpm db:prod:seed`

then youll see the issue on the challenges

**Comment by bautistaaa** [comment]
added steps to see it on the UI
