### ISSUE TITLE
[Feature]: Indicate if a comment is edited

### ISSUE THREAD

**Issue by BabisDigos** [typehero/typehero#905]
### Description

Could there be an indication that the 2nd comment has been edited?

![image](https://github.com/typehero/typehero/assets/85764745/6e362df9-4880-457c-846b-83c17e6315ce)

**Comment by zaCKoZAck0** [comment]
![image](https://github.com/typehero/typehero/assets/69889382/a2403c58-6c6c-4f05-82f9-88a7f691ae6a)
Something like this?

**Comment by bautistaaa** [comment]
this is a good idea

**Comment by oreoluwa-bs** [comment]
Can I work on this?

**Comment by odicho** [comment]
@oreoluwa-bs No pressure here, but are you still working on this? Let me know if not since I'm combing through issues today!

**Comment by oreoluwa-bs** [comment]
@odicho Yeah I am
