### ISSUE TITLE
[Bug]: Shared Solutions in profile should link directly to the solution

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#919]
### What happened?

these take me to the challenge. 

- also time is underline which makes it look like a link, remove the underline

<img width="1320" alt="CleanShot 2023-10-20 at 13 22 44@2x" src="https://github.com/typehero/typehero/assets/3660667/50615517-2cb1-4e52-aaa5-532ee5cdadba">

**Comment by bautistaaa** [comment]
cc @odicho

**Comment by odicho** [comment]
Awesome! Thanks for letting me know, that's funny someone just put challenges in that section 😂😂 and I didn't even notice 🤷

I'll sort this out today!
