### ISSUE TITLE
[Bug]: Error squiggly lines should not be present in test cases.

### ISSUE THREAD

**Issue by zaCKoZAck0** [typehero/typehero#926]
### What happened?

Error squiggly lines should not be present in test cases.
![image](https://github.com/typehero/typehero/assets/69889382/9932a023-250f-4515-aa26-6102db2cb075)
It should be like this
![image](https://github.com/typehero/typehero/assets/69889382/e98e2e34-457a-4d4c-9f8c-d6ca8f05b22d)

### What browsers are you seeing the problem on?

All

**Comment by bautistaaa** [comment]
they should def be in the test cases. how would you know which tests are passing?

**Comment by zaCKoZAck0** [comment]
There should be a count also instead of only squiggly lines, if it's possible.
