### ISSUE TITLE
Solutions UI improvement

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#928]
![image](https://github.com/typehero/typehero/assets/31113245/f98c3f58-24f5-47fe-8381-04513a16fd33)

instead of empty bar wasting vertical space, add a back arrow https://lucide.dev/icons/arrow-left next to the pfp inside a circle matching the size of the pfp circle.

![image](https://github.com/typehero/typehero/assets/31113245/51a3eb91-843d-41ec-8f61-a0c14331e843)

optionally, put buttons to the next line to match the challenge layout with name&date on one line and buttons on the next
![image](https://github.com/typehero/typehero/assets/31113245/6788bbf3-15ae-449c-a9ea-de513a75c817)

**Comment by krishpatel023** [comment]
Hey can you assign it to me?

**Comment by PickleNik** [comment]
> Hey can you assign it to me?

assigned, I've also added one more thing to the issue description

**Comment by krishpatel023** [comment]
I'll look into it @PickleNik

**Comment by PrathameshSonje** [comment]
Hey can I work on this issue ?

**Comment by PickleNik** [comment]
> Hey can I work on this issue ?

yeah, best/first PR wins i guess
