### ISSUE TITLE
[Bug]: Challenge Layout LeftPanel resets on navigation

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#929]
### What happened?

when leftPanel is collapsed (all the way to the left where it turns into icons), the panel should un-collapse upon navigation.

but when the leftPanel has been adjusted to be wider, it should keep the width preference after the navigation to other tabs.

https://github.com/typehero/typehero/assets/31113245/de679828-08ab-46c7-a61f-ae2c261c0381

NOTE: it still keeps preference after a page refresh, that part is working, but it resets every time you navigate to another tab

### What browsers are you seeing the problem on?

All

**Comment by zaCKoZAck0** [comment]
Can I try this one!?
