### ISSUE TITLE
[Bug]: Explore page skeletons on larger screens

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#930]
### What happened?

Explore page skeletons need to be adjusted to match content layout (to have the same padding on the left as `.container` constraints), currently it's all the way to the left which doesn't match the carousel content that has padding to align with container.
<img width="1728" alt="Screenshot 2023-10-21 at 1 33 57 PM" src="https://github.com/typehero/typehero/assets/31113245/89654ec1-0afc-4265-acce-8f253c0cab5e">

**Comment by G-R3** [comment]
can I give this a shot king?
