### ISSUE TITLE
[Feature]: Better Notifications UI

### ISSUE THREAD

**Issue by PickleNik** [typehero/typehero#943]
### Description

make it look like dis:

![image](https://github.com/typehero/typehero/assets/31113245/e7c9cddd-6f08-4855-b07d-34d0a9e94cfe)

background can be implemented using linear-gradients similar to how grid is implemented on the landing page (see `hero.tsx`)

**Comment by sital002** [comment]
I would like to work on this issue.

**Comment by sital002** [comment]
I am not able to  import the backgroundgrid component in ```toaster.tsx``` file

**Comment by PickleNik** [comment]
> I am not able to import the backgroundgrid component in `toaster.tsx` file

u don't have to, it's too big of a grid for it anyways and has no color, just make a new one

**Comment by fitrahfm** [comment]
@PickleNik would love to work on it

**Comment by PickleNik** [comment]
> @PickleNik would love to work on it

Go for it

**Comment by Mahmoudgalalz** [comment]
Assign it to me Will work on it

**Comment by Mahmoudgalalz** [comment]
@PickleNik Are we going to remove the actions? our leave it

meaning, tweak the above design but follow the toaster 

and does the background follow dark, light mode?

**Comment by ouichniaziz** [comment]
Hello anyone still working on this issue ?

**Comment by bautistaaa** [comment]
dont think so

**Comment by ouichniaziz** [comment]
PR : [https://github.com/typehero/typehero/pull/1288](url)
