### ISSUE TITLE
[Feature]: Challenge view cleanup

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#944]
### Description

Currently the default of the editor font and prompt are different. Prompt (16px) and Editor (13px). They should align at least by default.

Additionally, the code blocks in the prompt should match the same font as the rest of the prompt

- [ ] default editor to 16px or whatever the size is in the markdown prompt
- [ ] code blocks in the prompt should be the same font size as the rest of the prompt
- [ ] decrease line height in the markdown prompt to 1.5rem

### Explanation

This will make the whole reading/writing experience feel more connected.

**Comment by oreoluwa-bs** [comment]
Can I work on this?

**Comment by bautistaaa** [comment]
> Can I work on this?

yes we need this asap though

**Comment by odicho** [comment]
If this isn't done by EOD, I'll take a stab at it as well!

**Comment by bautistaaa** [comment]
> If this isn't done by EOD, I'll take a stab at it as well due to the high priority.

cool we’re in whoever submits a PR first wins phase
