### ISSUE TITLE
[Bug]: promise.all challenges error

### ISSUE THREAD

**Issue by roiiiu** [typehero/typehero#971]
### What happened?

<img width="904" alt="image" src="https://github.com/typehero/typehero/assets/11494827/5270dbb5-cbc3-4234-b239-2432d8ceb986">
<img width="1078" alt="image" src="https://github.com/typehero/typehero/assets/11494827/5a8a27c1-e43b-4811-b13d-40c179d420c6">

### What browsers are you seeing the problem on?

Chrome

**Comment by saman-taghavi** [comment]
yep, I encountered the same error on this page [https://typehero.dev/challenge/promise.all](promise.all)

**Comment by bautistaaa** [comment]
thanks for catching i’ll fix!

**Comment by maxdemaio** [comment]
Ayo, I can take a look at this but I think if we rename the challenge to `promise-all` or `promiseall` that may fix it 👍🏻
