### ISSUE TITLE
[Bug?]: Challenge - Generic Function Arguments - Wrong test types?

### ISSUE THREAD

**Issue by ardeora** [typehero/typehero#974]
### What happened?

First of all, thank you so much for the early access! TypeHero is absolutely beautiful and I am absolutely enjoying everything about it. I wanted to check if this behavior is a bug or not. If not feel free to close this issue.

URL: https://typehero.dev/challenge/generic-function-arguments

<img width="1652" alt="Screenshot 2023-10-27 at 2 28 51 PM" src="https://github.com/typehero/typehero/assets/45807386/daaaeb47-1b31-497c-be20-d9547ecf1044">

On this challenge, we're asked to implement an `identity` function that takes in a value and returns it while also correctly inferring the return value types. I think I have implemented the solution correctly but the test cases seem to fail. This is because the test cases it's trying to check against a more looser type of the returned value.

For example

```ts
const my_val = identity('this is a string')
```

The type of `my_val` is correctly inferred as `this is a string` but the test case expects it to be of type `string` and fails if the type is not exactly `string`. Is this an expected behavior?

### What browsers are you seeing the problem on?

All

The only solution on that page seems like a hacky way to circumvent the test cases. It would be helpful to update the description to give a hint to the user how the answer should be accomplished, Since it's a beginner level question!

Thanks in advance!

**Comment by bautistaaa** [comment]
currently on travel

cc @dimitropoulos

**Comment by dimitropoulos** [comment]
@ardeora thanks for the report!  pretty exciting to see people working on these :)

hope you like what you've seen so far and please keep any feedback coming!
