### ISSUE TITLE
[Feature]: Add vercel event for enroll/unenroll button on /tracks

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#986]
### Description

We current have an event for the submit button challenges. Lets add new ones for unenroll/enroll actions and log the track name as well. We currently have one track so it technically doesnt matter but as we scale tracks it will make sense.

**Comment by zaCKoZAck0** [comment]
What all is to track, only `track` name?

**Comment by zaCKoZAck0** [comment]
`track?.('track-enrolled', {
            trackId,
            trackName: text,
          });`

**Comment by bautistaaa** [comment]
> `track?.('track-enrolled', { trackId, trackName: text, });`

can just be slug and whether not it was enrolled/unenrolled
