### ISSUE TITLE
[Bug]: Markdown renders type annotations like strings

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#987]
### What happened?

Type annotations should have a different color

<img width="498" alt="CleanShot 2023-10-29 at 07 40 41@2x" src="https://github.com/typehero/typehero/assets/3660667/ab861afb-bcbb-44db-9482-986cfdf91be8">

**Comment by Hacksore** [comment]
we should be using the same theme in monaco and the markdown renderer if possible 😅

<img width="967" alt="image" src="https://github.com/typehero/typehero/assets/996134/bcc602d4-a178-47dc-80c5-a929ed9baf10">

**Comment by bautistaaa** [comment]
what does monaco use. it’s currently using vsc and vscdark

**Comment by PhantomKnight287** [comment]
The theme used by the markdown renderer closely resembles one dark
