### ISSUE TITLE
[Bug][Challenge] Index Signatures no proper test cases

### ISSUE THREAD

**Issue by niemal** [typehero/typehero#989]
### What happened?

I passed all test cases with the following code (thing which shouldn't be the case):

```ts
type GroceryList = {
	[item: string]: number;
}
type InappropriateActionBySituation = unknown;

type CharactersById = unknown;
```
![](https://i.imgur.com/4zShC8K.png)

Link to the code with the challenge: https://typehero.dev/challenge/index-signatures?code=C4TwDgpgBA4gTgewMYTiAMgSwM7CgXigG8AoASAG1NgIBbALilzkwDsBzAXUdYFdaARqgDcJAL4lQkKAElWAQzBhEyzPJoBBJMEwJWAIRABlar3W7WBKL1YBrVggDurUZPDQAwgAt5cedtRsQxkAEysbeycXEiA

The same code passes all test cases on the TS playground: https://www.typescriptlang.org/play#code/C4TwDgpgBA4gTgewMYTiAMgSwM7CgXigG8BYAKAEgBtTYCAWwC4pc5MA7AcwF1n2BXegCNUAbnIBfcuVCQoASXYBDMGERrMSugEEkwTAnYAhEAGVa-LQfYEo-dgGt2CAO7txZGeGgBhABZKcEp6qNgm8gAmtvZOru7SnmRIhrhQnIgoaFi4zPDIqBg4eISkZFBQSIGIwNjMAKwANOTlYAjAWggQtVAAjABMTWUsLhAQwAAKbR1dzAPNUMD8cOyYYN09gy2B2CtrzBvzImPrAAybUEEROH4zUHNDcPztQkqcSuvnhtbdAMznb3AADaYJCzQbzAD0EKgAAEagBaCAAD0gekRcEQcCgHDo7H0hiUgMBIGx7AAboTMBF5tg-Ah+ICIgBRDEIODMABEIkq-Gw0FoAHJsFAlCxgGwuBzwUMobCEcjUcB0ZjSbj8coiSSOBTgdShrT6YztIDsAgWZjmOL+BBJB5yMl2KkOCo1AgNFoILp1SZzIsrIZmIoXeo2B6vdYfRZ-TYSvMAGb2VCE5hUAXIlDYbCYMnQQFKficPx0OAChpQAVCCWcDicOxgKCQOCmjUipB+TAQHP0CB47AC7jnbtXSqAgAimk4ziz3VTACsEA4uiKhPS8Npu2xKjYboTgH5KnAIKXywB1CBCACyo+PAoiCAQ9GwSEQRJrCxctGLpNwECUUQQcZQMCP4rFw-bnICozAMkEQQIoxZkh2LgpgKahKDg0AAVAPimKYN5ILQb4ABoANI+KOFQPiCwpCCSAjCKgUBxog9BQN29BsiAN68phgEMAgs44KSUAuO2dAroEUTIqgBF8sKcYIESrgQFEtENoY+hxiCVhcMuq5QCA9JYrBED1rELiQREnC8VAACqAAqABi8I9AAbOB8ZsD2zIoqgHbsARXAABK-nAwCVr+DgoYheicVAERKAF0DcvmfIGfSUABHQUR7hAmBYqYAB0ADyhU3gBcahAsCALEsNiGAsNy9AAnK1FQcAwVhIGx7zFmAHYoGW9lNRegj0CAZYfnuUBGIe7AJTYjlBHyWKJVEABKwQ3ICUBnjgABeHlkBIdpJCkeBtoEwTFmEICRMw-hXSETbhFEsZDD0zClOU5RUvs5zlMo3acutIIOFApiJW2ED7VK8zlLgWi8pyxrZhAcNDAjqIdt0HJBYIiUY+UEjnH0X3w9iERghTQMQJyF5sqAEP0LQfhEz9iOLLjqM5uzWMQARtx4wT7DsyT8w-OTmOU8wfw00owNQByphjYxpgs3ufNikj3PArzAMsNjQv4-QhPnOLQwACxSz9MtQJbBu05yRhjH4zOs1rnPI0rPPowb2BG7jJtm-MFvlHUNs-X9UCNPLiscgAUqgaDu5r-vtFzKN637FMBwLOOcsHovm4MJ3kEAA

**Comment by bautistaaa** [comment]
cc @dimitropoulos

**Comment by niemal** [comment]
I am thinking a solution to this is something along the lines of: 
```typescript
type testCaseGroceryList = Expect<NotEqual<GroceryList, unknown>>;
type testCaseInappropriateActionBySituation = Expect<NotEqual<InappropriateActionBySituation, unknown>>;
type testCaseCharactersById = Expect<NotEqual<CharactersById, unknown>>;
```

https://www.typescriptlang.org/play?#code/C4TwDgpgBA4gTgewMYTiAMgSwM7CgXigG8BYAKAEgBtTYCAWwC4pc5MA7AcwF1n2BXegCNUAbnIBfcuVCQoASXYBDMGERrMSugEEkwTAnYAhEAGVa-LQfYEoQhAgA2EJe3FkZ4aAGEAFkrglPVRsE3kAE1t+dgBrdgQAdzdpDzIAejSoOlwoJCVsCGwoAFpigD5POQBRAA9IPQAeABUoCBq6dnCi4Dh+CDLbAApmssGASgIBlraOrqgWgH4oAEYoZgAmCZmITqKR8cn51vaduZ6+qCXVjcus3uhmADMlRwLK6AA5BGAqgEdLRwNAAaABooABNAaEYZNUYTfBTY6zIpA27XKCbJGnPawg4Io7bXYQtFrDG3Z6vB53PopWTQbLAbz5CDwZCoDA4PCEWr1YANL4-f4vBqslBoLC4MHROKJdhlMruOlZQqM5mKFRqBAaLQQXT6QwmczASz6mzcuoQRoCv4Ahrq1TqNg6vXWQ0WKyGKWxeJJeWKrzK3BMgp+AJBOhwUIgCK2HmWvnWoWA0OBYKRsLhL0y30KlJIQw5TiIMUc3DMUXsiVc4jkKC5AKIYDYZgAVhBtagYG+WgQhWYy3W7bIdewCQgEGAAAVu8Be82MUO68a4OxMGB58tF52AthV+v+1uRBONwAGLeBcI4Xx9hcd3rAJRCJScfIHjuGazzgDMW5fcEcmBIBsQ4dhkUAAAJNsUbS8tBcCIHAUAcB0povI4IBIewABuLyYOEHbYL4CD8I44RVPBCBwMwABEIh5PwBRIcAADkRRKCwPQcJw1EgcOUBgZB2DQRaehwQhmEodYaEYRwOEAfhfGEcRpHaK8CDkQhzDnBAkjuOQ+bsDkHAao6mg6HorpmO6prMPamrauZppusaHpmjWfGPNEqAvMwVDMW0KDYNgmBYdAjhKPwnC+BGzFgsxQhsFwXFQPwYCdiEhgvFAQS+JgEChfQOxNsx3BboVl55I4AAimicPEwXzn5ABWCAxIU2X2PweDaIVbB5DY14vMAvh5HAECxVAzEAOoQEIACyVUTcx4QOPQ2BIIgjgAVwWQJLQEaYbgLiRAgjxQABR2rlwJVbs4E75uEECKBGWF5QkvnMWoSg4NAp1QN4pimEtSC0MlQIANLeFVuQIPQgFFEIGECMIqBQI8iD0FAhX0JRIBLQxv1nQwCBNTgmFQAkuV0PYASRG0qAgwURSPE4jiJBAkSI52hj6I8gFWDtj7EXgIDEYhj0QGl2bOOEnCE1AACqTQAGLFMsABsN0dujeWdHGbA7CDXAABIuHAwAJS4MQfa9ei41A4SuCgdiWhFjGi-wUD+HQkTDRAmCIaYAB0ADyQdLadjwhFkCBZPwK5QIYWTXisACc6e5BwDBWEgWP5BGYB5SgYJNCnc2CPQIBgntw1QEYY2dK4UDK4EBSIa4kQAEo5RAjhQDNOAAF5a2QEh6WQBk5Eg-iphGUYRMwKbhiEGa2KQfHLMw691nWeFvnxdbKIVNGd4BMRQKYTvXoPPEdiOD7GvO1GqSFEC3wfLD1HlT-G4Irjv3WCQW51hbzvkhcIwEwFHwgDROalFQAXzhsNABO9cBaAYjRF+oUUEji-jeaiv96D-y3EAjsX5QEfz3lAH8UClDHygNRUwFdUamCQb4HBHF0FPywW-LcuDLTfxooQ4hHZSF8QACwUJ3uA5g4i+FQGgTRIwE5fCINoOw+RaDH6YIAtgzReCf5-3YCgsRdYWxSJ3lQtstD6HUQAFKoDQGo5BmiH4YIYTwjh2ADFCKMSYocY9yBAA
