### ISSUE TITLE
[Feature]: Indicator a challenge has been solved on the challenge card

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#993]
### Description

Currently, theres no way to tell you completed a challenge unless youre in the context of a track.

A couple things we should do

- [ ] change sorting of each category on explor from not done -> done
- [ ] profile page needs a completed section
- [ ] challenge UI needs some indicator that it has been solved
- [ ] explore cards needs some indicator that it has been solved

**Comment by ja153903** [comment]
@bautistaaa Is this what you had in mind for the challenge UI?
![Screenshot 2023-10-29 at 9 24 18 PM](https://github.com/typehero/typehero/assets/20523874/8f1ffcec-c6c7-4ce0-9f1e-d08a9dfd5ea9)
![Screenshot 2023-10-29 at 9 24 10 PM](https://github.com/typehero/typehero/assets/20523874/1479f0b4-c163-47b3-a0f2-21a253e51462)

**Comment by ja153903** [comment]
@bautistaaa For the completed section, do we want to do something like this on the profile page?

<img width="1484" alt="Screenshot 2023-10-31 at 11 27 43 AM" src="https://github.com/typehero/typehero/assets/20523874/293fc473-b7a5-4dd2-886f-a918cdc6cb1c">

**Comment by bautistaaa** [comment]
yup!

**Comment by jselmani** [comment]
Looks like this was completed in #1014.  Can we close this?
