### ISSUE TITLE
[Feature]: Editor needs formatter shortcut

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#994]
### Description

Currently theres no way to format your code. We should add shortcuts (ex: cmd + shift+ f) and an explicit button where the setting are

**Comment by ggrandi** [comment]
This should already exist. If you right-click, there's an option to format your code which shows a keyboard shortcut.
If you want you can also add it to the vim keybinds by:
```
nmap <Some-Keybind> :M<Space>editor.action.format
```
