### ISSUE TITLE
[Feature]: Push user to another challenge after solving

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#995]
### Description

Currently after solving a challenge it just gives you a dismiss button the the successful toast. We should either push them to the explore page or a next challenge. Unsure where this should go atm

leetcode shows "more challenges"

<img width="838" alt="CleanShot 2023-10-29 at 15 52 58@2x" src="https://github.com/typehero/typehero/assets/3660667/992b0049-5bf9-4aa1-9a87-ab89b899d091">

**Comment by zaCKoZAck0** [comment]
Next challenge if following a track?

**Comment by bautistaaa** [comment]
> Next challenge if following a track?

yes in that case

**Comment by Mahmoudgalalz** [comment]
I was going to do that, can I work on it ?
